### ISSUE TITLE
CUDA_HOME ImportError with mmcv >= 1.3.11

### ISSUE THREAD

**Issue by shinya7y** [open-mmlab/mmgeneration#102]
https://github.com/open-mmlab/mmcv/pull/1249 removed `CUDA_HOME` from `mmcv/utils/parrots_wrapper.py`.

https://github.com/open-mmlab/mmgeneration/blob/f8d6f2e204a8e8c18fdda744a8465e90d9f9fb68/mmgen/utils/collect_env.py#L26
should be fixed like
https://github.com/open-mmlab/mmcv/commit/9fa5de8b9b393340c5a1fe5166725dfcb229dfe0#diff-7d14e65d28f33c08baca2b18a93af3a3a47575395f0b30f4c0c790b505752ce1

**Comment by nbei** [comment]
Thanks @shinya7y . @LeoXing1996 will fix this bug accordingly.

**Comment by LeoXing1996** [comment]
Fixed in #103
