### ISSUE TITLE
cannot import name 'CUDA_HOME' from 'mmcv.utils.parrots_wrapper' 

### ISSUE THREAD

**Issue by wwjwy** [open-mmlab/mmgeneration#105]
when i run the code ,i meet this problem,can you help me?

mmgeneration/mmgen/utils/collect_env.py", line 26, in collect_env
    from mmcv.utils.parrots_wrapper import CUDA_HOME
ImportError: cannot import name 'CUDA_HOME' from 'mmcv.utils.parrots_wrapper'
cannot import name 'CUDA_HOME' from 'mmcv.utils.parrots_wrapper'

**Comment by LeoXing1996** [comment]
We had already fix this in #103. Please update your mmgen by pulling the newest branch.
