### ISSUE TITLE
AssertionError in metrics.py

### ISSUE THREAD

**Issue by weivision** [open-mmlab/mmgeneration#106]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmgeneration.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```
sh tools/slurm_train.sh test mmg_cifar10 configs/biggan/biggan_cifar10_32x32_b25x2_500k.py exps/biggan-cifar10
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No

3. What dataset did you use?
CIFAR10

**Environment**

1. Please run `python mmgen/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```
INFO:mmgen:Sample 50000 fake images for evaluation
[                                                  ] 0/50000, elapsed: 0s, ETA:2021-09-05 15:49:32,938 - mmgen - INFO - `use_pil_resize` is set as True, apply Bicubic interpolat$on with Pillow backend. We perform type conversion between torch.tensor and PIL.Image in this function and make this process a little bit slow.
INFO:mmgen:`use_pil_resize` is set as True, apply Bicubic interpolation with Pillow backend. We perform type conversion between torch.tensor and PIL.Image in this function and make this process a little bit slow.
[>>>>>>>>>>>>>>>>>>>>>>>>] 50000/50000, 50.7 task/s, elapsed: 985s, ETA:     0s
Traceback (most recent call last):
  File "tools/train.py", line 163, in <module>
    main()
  File "tools/train.py", line 159, in main
    meta=meta)
  File "~/.local/lib/python3.6/site-packages/mmgen-0.3.0-py3.6.egg/mmgen/apis/train.py", line 198, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "~.local/lib/python3.6/site-packages/mmgen-0.3.0-py3.6.egg/mmgen/core/runners/dynamic_iterbased_runner.py", line 285, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "~/.local/lib/python3.6/site-packages/mmgen-0.3.0-py3.6.egg/mmgen/core/runners/dynamic_iterbased_runner.py", line 236, in train
    self.call_hook('after_train_iter')
  File "~/.local/lib/python3.6/site-packages/mmgen-0.3.0-py3.6.egg/mmgen/core/runners/dynamic_iterbased_runner.py", line 181, in call_hook
    getattr(hook, fn_name)(self)
  File "~/.local/lib/python3.6/site-packages/mmgen-0.3.0-py3.6.egg/mmgen/core/evaluation/eval_hooks.py", line 283, in after_train_iter
    metric.summary()
  File "~/.conda/conda_envs/miniconda3/envs/openmm-lab/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "~/.local/lib/python3.6/site-packages/mmgen-0.3.0-py3.6.egg/mmgen/core/evaluation/metrics.py", line 575, in summary
    assert feats.shape[0] >= self.num_images
AssertionError
srun: error:task 0: Exited with exit code 1
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by LeoXing1996** [comment]
In `configs/biggan/biggan_cifar10_32x32_b25x2_500k.py`, `inception_pkl` for evaluating FID is set as None, which means our code would use numbers of `num_images` images in the test set to extract inception stat before evaluation.
However, for the CIFAR10 dataset, the test set only contains **10k** images, that's why the images number checking at line 575 failed.
We advise you to extract inception_pkl by yourself with the following command:
```
# For CIFAR10
python tools/utils/inception_stat.py --data-cfg configs/_base_/datasets/cifar10_inception_stat.py --pklname cifar10.pkl --no-shuffle --inception-style stylegan --num-samples -1 --subset train

# For ImageNet1k
python tools/utils/inception_stat.py --data-cfg configs/_base_/datasets/imagenet_128x128_inception_stat.py --pklname imagenet.pkl --no-shuffle --inception-style stylegan --num-samples -1 --subset train
```
More descriptions about how to extract inception state can be found in this [link](https://github.com/open-mmlab/mmgeneration/tree/master/configs/sngan_proj).

**Comment by weivision** [comment]
Many thanks!
