### ISSUE TITLE
some questions when using mmg

### ISSUE THREAD

**Issue by wwjwy** [open-mmlab/mmgeneration#114]
When using the unconditional GANS model, can we only use one type of dataset for training? Does it support multiple types of training? 
当使用unconditional GANS 模型时，是不是只能使用一个种类的数据集进行训练，请问它都支持多个目标种类训练吗?

**Comment by nbei** [comment]
Of course, you can use multiply datasets in different types. However, we cannot guarantee a pleasing performance. Intuitively, the IS in unconditional  ImageNet is much lower than that in conditional ImageNet.

**Comment by wwjwy** [comment]
Which label format does onditional ImageNet use? Is it like the image classification task, the txt file corresponds to the category name of the image?
conditional ImageNet采用的标签形式是哪一种呢，是不是像图像分类任务一样，txt文件对应图片所属类别名称？

**Comment by LeoXing1996** [comment]
> Which label format does conditional ImageNet use? Is it like the image classification task, the txt file corresponds to the category name of the image?
> conditional ImageNet采用的标签形式是哪一种呢，是不是像图像分类任务一样，txt文件对应图片所属类别名称？

Yes, you may refer to the dataset config for [imagenet128x128](https://github.com/open-mmlab/mmgeneration/blob/master/configs/_base_/datasets/imagenet_128.py).
If you want to learn more about how txt files and labels are loaded, you may refer to [the source code in MMCls](https://github.com/open-mmlab/mmclassification/blob/master/mmcls/datasets/imagenet.py)。

**Comment by wwjwy** [comment]
Thanks a lot

**Comment by wwjwy** [comment]
If I have a data set of 512x512 and want to generate a 512x512 image, can I directly change the input and output image size in the code?

**Comment by LeoXing1996** [comment]
Yes, you may adjust the target size of `Resize` or the `RandomCrop` operations in the config. 
Such as config in the following line:
https://github.com/open-mmlab/mmgeneration/blob/bfd00c3b3de936554dc685d7cdc3cb32dc9d43ad/configs/_base_/datasets/imagenet_128.py#L12

**Comment by wwjwy** [comment]
Thank you very much!
