### ISSUE TITLE
help of num_samples's parser is wrong

### ISSUE THREAD

**Issue by Irvingkkk** [open-mmlab/mmgeneration#117]
https://github.com/open-mmlab/mmgeneration/blob/0032271c7923dc5b414b25b7daf349db561a94d7/tools/evaluation.py#L59

**Comment by plyfager** [comment]
Hi @[Irvingkkk](https://github.com/Irvingkkk). Thanks for your remind, I've fixed this in PR[119](https://github.com/open-mmlab/mmgeneration/pull/119).
