### ISSUE TITLE
visualization.py (NotImplementedError: There were no tensor arguments to this function)

### ISSUE THREAD

**Issue by jayagami** [open-mmlab/mmgeneration#130]
**Describe the bug**

Error during traininig a sample config: `cyclegan_lsgan_id0_resnet_in_1x1_270k_horse2zebra.py`

At first every thing is alright, each time when it comes to the VisualizeUnconditionalSamples, program stopped and raised `NotImplementedError`.

```pyhon
custom_hooks = [
    dict(
        type='VisualizeUnconditionalSamples',
        output_dir='training_samples',
        interval=1000)
]
```

```

  File "/home/root/git/jay-mmgeneration/mmgen/core/hooks/visualization.py", line 73, in after_train_iter
    img_cat = torch.cat(img_list, dim=3).detach()
NotImplementedError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors, or that you (the operator writer) forgot to register a fallback function.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Named, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, UNKNOWN_TENSOR_TYPE_ID, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

```

**Reproduction**

just run it, the data is saved in data dir.

```shell
tools/dist_train.sh configs/cyclegan/cyclegan_lsgan_id0_resnet_in_1x1_270k_horse2zebra.py 2
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

yes

3. What dataset did you use?

**Environment**

- conda py3.8
- pytoch 1.7
- lastest mmlab-full and mmgen

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```
[error.log](https://github.com/open-mmlab/mmgeneration/files/7271273/error.log)

**Bug fix**

I found the VisualizeUnconditionalSamples exited in default runtime, so I create a new hook without VisualizeUnconditionalSamples.

```python

custom_hooks = [
    # dict(
    #     type="MMGenVisualizationHook",
    #     output_dir="training_samples",
    #     res_name_list=["fake_b"],
    #     interval=100,
    # )
]
```

seems worked now

**Comment by plyfager** [comment]
Hi @jayagami , `VisualizeUnconditionalSamples` is a hook for sampling images from unconditional GANs. For `CycleGAN`, you can use `MMGenVisualizationHook` just like [this](https://github.com/open-mmlab/mmgeneration/blob/855c8ac449e6027083aa16bee8256cc4b5594734/configs/cyclegan/cyclegan_lsgan_id0_resnet_in_1x1_270k_horse2zebra.py#L85) .
