### ISSUE TITLE
Rename pypi package to mmgeneration

### ISSUE THREAD

**Issue by mmgen** [open-mmlab/mmgeneration#136]
Hello Devs,

Might you consider renaming your [package](https://pypi.org/project/mmgen) on pypi.org to `mmgeneration` or `mmgenerate`?  This would make it consistent with the Github repository name, or with the naming of your other packages. In addition, `mmgen` conflicts with the package name and repo name of The [MMGen](https://github.com/mmgen/mmgen) Project (also written in Python), which has existed on Github since 2013.

UPDATE: I see the name of your package itself is also `mmgen`. If this were changed to `mmgenerate`, for example, then both our packages could coexist on the same computer without conflict. This would also be consistent with the naming of your other packages, which use the infinitive form of the verb. For instance, with that of your `mmtracking` repo, whose package name is `mmtrack`.

**Comment by nbei** [comment]
Hi @mmgen , since changing the name may cause many problems to the users, we should be more careful about this. Hope you can understand and we don't have any plan to change the name of our PyPI package.

**Comment by mmgen** [comment]
You do realize that your package name causes problems for **our** users? In our case, `mmgen` is not just the name of a single package within a larger project -- it's our Github username and the name of the project itself, a project, I repeat, which has existed on Github since 2013.

As far as I can tell from looking at your code, this change would involve renaming one directory and one variable in `setup.py` -- not very much trouble from your point of view.

**Comment by mmgen** [comment]
> Hi @mmgen , since changing the name may cause many problems to the users, we should be more careful about this. Hope you can understand and we don't have any plan to change the name of our PyPI package.

You do realize that your package name causes problems for **our** users? In our case, `mmgen` is not just the name of a single package within a larger project -- it's our Github username and the name of the project itself, a project, I repeat, which has existed on Github since 2013.

As far as I can tell from looking at your code, this change would involve renaming one directory and one variable in `setup.py` -- not very much trouble from your point of view.

**Comment by mmgen** [comment]
> When we set up our package in PyPI, we have not found any conflicts in the PyPI site. Thus, we just use the name of `mmgen` as our package name. We cannot directly change the name, just because there is another project using the same name in PyPI. If there is another project with the name of `mmgeneration`, we will have to change the name again? We will have a further discussion about this issue, but I suggest that changing the name is not in our plan.

I think you're safe with either `mmgenerate` or `mmgeneration`. No one besides you has claimed those names either on Github or PyPI. Please do consider making this change. The MMGen Project would be most grateful for your cooperation. And more consistent naming is ultimately beneficial for your project and users as well, even if it causes some temporary inconvenience at first.

**Comment by mmgen** [comment]
So the pip package name remains `mmgen`?
