### ISSUE TITLE
Computation of FID at different scales - MSPIE

### ISSUE THREAD

**Issue by vglsd** [open-mmlab/mmgeneration#148]
Hello,

Thank you for the amazing work on Positional Encodings and the neat github repo!

I am trying to compute the FID at different scales and I was wondering about the process you followed to do so for MSPIE. 

Following your documentation, I am currently using 
`python tools/utils/inception_stat.py --imgsdir ${path-to-1024-FFHQ} --pklname ${out-pkl-destination} --size ${size-of-output-images-to-compare-with} --num-samples 50000
`
When using the produces pkl to compare with one of your pretrained models (usings tools/evaluate.py), I am getting an FID of ~19 for 256x256 images and I am trying to find what I am doing wrong.

Thanks!

Cheers,
Evan

**Comment by nbei** [comment]
There is some mistakes in your command.
* Firstly, you should explicitly resize the 1024-FFHQ dataset to 256-FFHQ dataset. Then, the `--imgsdir` should be set with the path for the `256-FFHQ`.
* `--size` will set the size of input images to the inception network. In general, the input shape of the pre-trained inception network should be (299, 299), which is our default setting in `tools/utils/inception_stat.py`

We have already provided the 256-FFHQ inception stat, which you can download from [here](https://download.openmmlab.com/mmgen/evaluation/fid_inception_pkl/ffhq-256-50k-rgb.pkl).

**Comment by vglsd** [comment]
Thanks for the help!
