### ISSUE TITLE
Differences between ModulatedPEConv2d and ModulatedConv2d

### ISSUE THREAD

**Issue by IceClear** [open-mmlab/mmgeneration#152]
Hi, I noticed that in Styleganv2, ModulatedConv2d is applied. However, there is also a ModulatedPEConv2d function, but seems not used in any model. So what is the difference between ModulatedPEConv2d and ModulatedConv2d. I haven't found any information related to this. Why not use ModulatedPEConv2d instead of ModulatedConv2d?  Actually, I saw some checkboard artifacts using Styleganv2 and it seems it is due to the [ConvTranspose2d operation](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/190). Thus, I wonder whether ModulatedPEConv2d can be applied to solve such a problem. Thanks.

**Comment by LeoXing1996** [comment]
`ModulatedPEConv2d` is used in [Positional Encoding as Spatial Inductive Bias in GANs](https://openaccess.thecvf.com/content/CVPR2021/html/Xu_Positional_Encoding_As_Spatial_Inductive_Bias_in_GANs_CVPR_2021_paper.html).
Please refer to the original paper and our [configs](https://github.com/open-mmlab/mmgeneration/blob/master/configs/positional_encoding_in_gans/README.md).

**Comment by IceClear** [comment]
Noted with thanks.
