### ISSUE TITLE
Some confusion about generative networks

### ISSUE THREAD

**Issue by wwjwy** [open-mmlab/mmgeneration#184]
Hello, I have some confusion about the generativeadversarial generative network, I hope I can get your help.
As some papers introduce that GAN can be used to generate images to expand the data set. My question is, if I want to train a GAN to generate the images to enlarge my dataset, do I need to provide a large training dataset for the GAN?

**Comment by LeoXing1996** [comment]
Train GAN with external data means the distribution of generated images belongs to the new dataset. If you just want to generate images for data augmentation, we do not recommend training your model with a new dataset. 
You may consider fine-tuning an off-the-shelf generator with your dataset, and this process does not need a great amount of data.

**Comment by wwjwy** [comment]
> Train GAN with external data means the distribution of generated images belongs to the new dataset. If you just want to generate images for data augmentation, we do not recommend training your model with a new dataset. You may consider fine-tuning an off-the-shelf generator with your dataset, and this process does not need a great amount of data.

Thank you very much for your reply.  Does training a generator from scratch usually require a lot of training data?

**Comment by LeoXing1996** [comment]
This depends on your dataset. You may need at least thousands of images empirically.

**Comment by wwjwy** [comment]
> This depends on your dataset. You may need at least thousands of images empirically.

Thanks a lot!
