### ISSUE TITLE
Could you display the file structure of the dataset? (e.g. horse2zebra, summer2winter, facade)?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmgeneration#190]
Hi, dear authors！
Thank you for your amazing job!
Could you release the folder structure of the dataset? (e.g. horse2zebra, summer2winter, facade)?
Thank you!

**Comment by plyfager** [comment]
Hi, @zhongqiu1245 , thanks for your attention to our project. The structure of the datasets is displayed at [docs](https://mmgeneration.readthedocs.io/en/latest/quick_run.html#datasets-for-image-translation-models). We just keep the structure of the original datasets.

**Comment by zhongqiu1245** [comment]
Thank you!
