### ISSUE TITLE
Can you provide a docker image to ease the use of this code?

### ISSUE THREAD

**Issue by ai-porter** [open-mmlab/mmgeneration#198]
Installing the prerequisites is somewhat complicated. Not all researchers are able to run on a server with all privileges. Will the community provide a  docker image of the prerequisites?

**Comment by LeoXing1996** [comment]
Hey @ai-porter, thank you for being interesting in our project.
We will consider this suggestion and support the docker image as soon as possible.

**Comment by LeoXing1996** [comment]
Dockerfile is provided. Close this issue.
