### ISSUE TITLE
Training times problem when using multi-gpus

### ISSUE THREAD

**Issue by ShoupingShan** [open-mmlab/mmgeneration#206]
**Question:**
When I train styleganv2 by using `bash tools/dist_train.sh configs/styleganv2/stylegan2_c2_ffhq_256_b4x8_800k.py 1`  (1 GPU) and `bash tools/dist_train.sh configs/styleganv2/stylegan2_c2_ffhq_256_b4x8_800k.py 2` (2GPU), but the training times are almost the same.

**logs:**
**1. `bash tools/dist_train.sh configs/styleganv2/stylegan2_c2_ffhq_256_b4x8_800k.py 1`**
    
/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py:164: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  "The module torch.distributed.launch is deprecated "
The module torch.distributed.launch is deprecated and going to be removed in future.Migrate to torch.distributed.run
WARNING:torch.distributed.run:--use_env is deprecated and will be removed in future releases.
 Please read local_rank from `os.environ('LOCAL_RANK')` instead.
INFO:torch.distributed.launcher.api:Starting elastic_operator with launch configs:
  entrypoint       : tools/train.py
  min_nodes        : 1
  max_nodes        : 1
  nproc_per_node   : 1
  run_id           : none
  rdzv_backend     : static
  rdzv_endpoint    : 127.0.0.1:29500
  rdzv_configs     : {'rank': 0, 'timeout': 900}
  max_restarts     : 3
  monitor_interval : 5
  log_dir          : None
  metrics_cfg      : {}

INFO:torch.distributed.elastic.agent.server.local_elastic_agent:log directory set to: /tmp/torchelastic_hym17szx/none_aujbtbrg
INFO:torch.distributed.elastic.agent.server.api:[default] starting workers for entrypoint: python
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
/opt/conda/lib/python3.7/site-packages/torch/distributed/elastic/utils/store.py:53: FutureWarning: This is an experimental API and will be changed in future.
  "This is an experimental API and will be changed in future.", FutureWarning
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_hym17szx/none_aujbtbrg/attempt_0/0/error.json
fatal: not a git repository (or any parent up to mount point /home/ma-user)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

2022-01-06 23:05:39,038 - mmgen - INFO - Environment info:
------------------------------------------------------------

sys.platform: linux
Python: 3.7.10 (default, Jun  4 2021, 14:48:32) [GCC 7.5.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GPU 0,1: Tesla P100-PCIE-16GB
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.9.0+cu102
PyTorch compiling details: PyTorch built with:

  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.0+cu102
OpenCV: 4.5.5
MMCV: 1.4.0
MMGen: 0.4.0+
MMCV Compiler: GCC 7.3

MMCV CUDA Compiler: 10.2
------------------------------------------------------------

2022-01-06 23:05:39,172 - mmgen - INFO - Distributed training: True
2022-01-06 23:05:39,303 - mmgen - INFO - Config:
dataset_type = 'UnconditionalImageDataset'
train_pipeline = [
    dict(type='LoadImageFromFile', key='real_img', io_backend='disk'),
    dict(type='Flip', keys=['real_img'], direction='horizontal'),
    dict(
        type='Normalize',
        keys=['real_img'],
        mean=[127.5, 127.5, 127.5],
        std=[127.5, 127.5, 127.5],
        to_rgb=False),
    dict(type='ImageToTensor', keys=['real_img']),
    dict(type='Collect', keys=['real_img'], meta_keys=['real_img_path'])
]
val_pipeline = [
    dict(type='LoadImageFromFile', key='real_img', io_backend='disk'),
    dict(
        type='Normalize',
        keys=['real_img'],
        mean=[127.5, 127.5, 127.5],
        std=[127.5, 127.5, 127.5],
        to_rgb=True),
    dict(type='ImageToTensor', keys=['real_img']),
    dict(type='Collect', keys=['real_img'], meta_keys=['real_img_path'])
]
data = dict(
    samples_per_gpu=4,
    workers_per_gpu=4,
    train=dict(
        type='RepeatDataset',
        times=100,
        dataset=dict(
            type='UnconditionalImageDataset',
            imgs_root='../../../data/raw/sample',
            pipeline=[
                dict(
                    type='LoadImageFromFile',
                    key='real_img',
                    io_backend='disk'),
                dict(type='Flip', keys=['real_img'], direction='horizontal'),
                dict(
                    type='Normalize',
                    keys=['real_img'],
                    mean=[127.5, 127.5, 127.5],
                    std=[127.5, 127.5, 127.5],
                    to_rgb=False),
                dict(type='ImageToTensor', keys=['real_img']),
                dict(
                    type='Collect',
                    keys=['real_img'],
                    meta_keys=['real_img_path'])
            ])),
    val=dict(
        type='UnconditionalImageDataset',
        imgs_root='../../../data/raw/sample',
        pipeline=[
            dict(type='LoadImageFromFile', key='real_img', io_backend='disk'),
            dict(
                type='Normalize',
                keys=['real_img'],
                mean=[127.5, 127.5, 127.5],
                std=[127.5, 127.5, 127.5],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['real_img']),
            dict(
                type='Collect', keys=['real_img'], meta_keys=['real_img_path'])
        ]))
d_reg_interval = 16
g_reg_interval = 4
g_reg_ratio = 0.8
d_reg_ratio = 0.9411764705882353
model = dict(
    type='StaticUnconditionalGAN',
    generator=dict(
        type='StyleGANv2Generator', out_size=256, style_channels=512),
    discriminator=dict(type='StyleGAN2Discriminator', in_size=256),
    gan_loss=dict(type='GANLoss', gan_type='wgan-logistic-ns'),
    disc_auxiliary_loss=dict(
        type='R1GradientPenalty',
        loss_weight=80.0,
        interval=16,
        norm_mode='HWC',
        data_info=dict(real_data='real_imgs', discriminator='disc')),
    gen_auxiliary_loss=dict(
        type='GeneratorPathRegularizer',
        loss_weight=8.0,
        pl_batch_shrink=2,
        interval=4,
        data_info=dict(generator='gen', num_batches='batch_size')))
train_cfg = dict(use_ema=True)
test_cfg = None
optimizer = dict(
    generator=dict(type='Adam', lr=0.0016, betas=(0, 0.9919919678228657)),
    discriminator=dict(
        type='Adam', lr=0.0018823529411764706, betas=(0, 0.9905854573074332)))
checkpoint_config = dict(interval=10000, by_epoch=False, max_keep_ckpts=30)
log_config = dict(interval=100, hooks=[dict(type='TextLoggerHook')])
custom_hooks = [
    dict(
        type='VisualizeUnconditionalSamples',
        output_dir='training_samples',
        interval=5000),
    dict(
        type='ExponentialMovingAverageHook',
        module_keys=('generator_ema', ),
        interval=1,
        interp_cfg=dict(momentum=0.9977843871238888),
        priority='VERY_HIGH')
]
runner = dict(
    type='DynamicIterBasedRunner',
    is_dynamic_ddp=True,
    pass_training_status=True)
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = '../../../model_zoo/mmgeneration/0.4.0/styleganv2/stylegan2_c2_ffhq_256_b4x8_20210407_160709-7890ae1f.pth'
resume_from = None
workflow = [('train', 10000)]
find_unused_parameters = True
cudnn_benchmark = True
ema_half_life = 10.0
lr_config = None
total_iters = 5000
metrics = dict(
    fid50k=dict(
        type='FID',
        num_images=40000,
        inception_pkl='../../../output/inception_pkl/sample.pkl',
        bgr2rgb=True),
    pr50k3=dict(type='PR', num_images=40000, k=3),
    ppl_wend=dict(type='PPL', space='W', sampling='end', num_images=40000))
evaluation = dict(
    type='GenerativeEvalHook',
    interval=10000,
    metrics=dict(
        type='FID',
        num_images=40000,
        inception_pkl='../../../output/inception_pkl/caleba.pkl',
        bgr2rgb=True),
    sample_kwargs=dict(sample_model='ema'))
work_dir = './work_dirs/stylegan2_c2_ffhq_256_b4x8_800k'
gpu_ids = range(0, 1)

2022-01-06 23:05:39,304 - mmgen - INFO - Set random seed to 2021, deterministic: False
2022-01-06 23:05:41,097 - mmgen - INFO - dataset_name: <class 'mmgen.datasets.unconditional_image_dataset.UnconditionalImageDataset'>, total 40000 images in imgs_root: ../../../data/raw/sample
fatal: not a git repository (or any parent up to mount point /home/ma-user)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2022-01-06 23:05:44,954 - mmgen - INFO - dataset_name: <class 'mmgen.datasets.unconditional_image_dataset.UnconditionalImageDataset'>, total 40000 images in imgs_root: ../../../data/raw/sample
/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/torchvision/models/inception.py:82: FutureWarning: The default weight initialization of inception_v3 will be changed in future releases of torchvision. If you wish to keep the old behavior (which leads to long initialization times due to scipy/scipy#11299), please set init_weights=True.
  ' due to scipy/scipy#11299), please set init_weights=True.', FutureWarning)
2022-01-06 23:08:41,239 - mmgen - INFO - FID: Adopt Inception in pytorch style
2022-01-06 23:08:41,271 - mmgen - INFO - Load reference inception pkl from ../../../output/inception_pkl/caleba.pkl
2022-01-06 23:08:41,272 - mmgen - INFO - load checkpoint from local path: ../../../model_zoo/mmgeneration/0.4.0/styleganv2/stylegan2_c2_ffhq_256_b4x8_20210407_160709-7890ae1f.pth
2022-01-06 23:08:41,581 - mmgen - INFO - Start running, host: ma-user@notebook-8057cc96-2d5a-4a22-9d1f-754b14633e6b, work_dir: /home/ma-user/work/mmgen/algorithms/mmgeneration/algorithm/work_dirs/stylegan2_c2_ffhq_256_b4x8_800k
2022-01-06 23:08:41,582 - mmgen - INFO - workflow: [('train', 10000)], max: 5000 iters
2022-01-06 23:08:41,582 - mmgen - INFO - Checkpoints will be saved to ./work_dirs/stylegan2_c2_ffhq_256_b4x8_800k/ckpt/stylegan2_c2_ffhq_256_b4x8_800k by HardDiskBackend.
/home/ma-user/work/mmgen/algorithms/mmgeneration/algorithm/mmgen/ops/conv2d_gradfix.py:190: UserWarning: conv2d_gradfix not supported on PyTorch 1.9.0+cu102. Falling back to torch.nn.functional.conv2d().
  f'conv2d_gradfix not supported on PyTorch {torch.__version__}. '
2022-01-06 23:10:34,715 - mmgen - INFO - Iter [100/5000]        lr_generator: 1.600e-03 lr_discriminator: 1.882e-03, eta: 1:11:51, time: 0.880, data_time: 0.003, memory: 12927, loss_disc_fake_g: 1.3611, loss_path_regular: 0.0610, loss: 1.1599, loss_disc_fake: 0.4977, loss_disc_real: 0.5007, loss_r1_gp: 2.3067
2022-01-06 23:11:54,224 - mmgen - INFO - Iter [200/5000]        lr_generator: 1.600e-03 lr_discriminator: 1.882e-03, eta: 1:06:59, time: 0.795, data_time: 0.003, memory: 12927, loss_disc_fake_g: 1.0434, loss_path_regular: 0.0636, loss: 1.2430, loss_disc_fake: 0.5775, loss_disc_real: 0.5714, loss_r1_gp: 1.9658
2022-01-06 23:13:13,804 - mmgen - INFO - Iter [300/5000]        lr_generator: 1.600e-03 lr_discriminator: 1.882e-03, eta: 1:04:30, time: 0.796, data_time: 0.003, memory: 12927, loss_disc_fake_g: 1.0855, loss_path_regular: 0.0574, loss: 1.2338, loss_disc_fake: 0.5709, loss_disc_real: 0.5621, loss_r1_gp: 1.8754

**2. `bash tools/dist_train.sh configs/styleganv2/stylegan2_c2_ffhq_256_b4x8_800k.py 2`**
/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py:164: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  "The module torch.distributed.launch is deprecated "
The module torch.distributed.launch is deprecated and going to be removed in future.Migrate to torch.distributed.run
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
WARNING:torch.distributed.run:--use_env is deprecated and will be removed in future releases.
 Please read local_rank from `os.environ('LOCAL_RANK')` instead.
INFO:torch.distributed.launcher.api:Starting elastic_operator with launch configs:
  entrypoint       : tools/train.py
  min_nodes        : 1
  max_nodes        : 1
  nproc_per_node   : 2
  run_id           : none
  rdzv_backend     : static
  rdzv_endpoint    : 127.0.0.1:29500
  rdzv_configs     : {'rank': 0, 'timeout': 900}
  max_restarts     : 3
  monitor_interval : 5
  log_dir          : None
  metrics_cfg      : {}

INFO:torch.distributed.elastic.agent.server.local_elastic_agent:log directory set to: /tmp/torchelastic_x1xrygdm/none_7_m468vp
INFO:torch.distributed.elastic.agent.server.api:[default] starting workers for entrypoint: python
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
/opt/conda/lib/python3.7/site-packages/torch/distributed/elastic/utils/store.py:53: FutureWarning: This is an experimental API and will be changed in future.
  "This is an experimental API and will be changed in future.", FutureWarning
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0, 1]
  role_ranks=[0, 1]
  global_ranks=[0, 1]
  role_world_sizes=[2, 2]
  global_world_sizes=[2, 2]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_x1xrygdm/none_7_m468vp/attempt_0/0/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker1 reply file to: /tmp/torchelastic_x1xrygdm/none_7_m468vp/attempt_0/1/error.json
fatal: not a git repository (or any parent up to mount point /home/ma-user)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /home/ma-user)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2022-01-06 23:14:12,988 - mmgen - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.7.10 (default, Jun  4 2021, 14:48:32) [GCC 7.5.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GPU 0,1: Tesla P100-PCIE-16GB
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.9.0+cu102
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.0+cu102
OpenCV: 4.5.5
MMCV: 1.4.0
MMGen: 0.4.0+
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.2
------------------------------------------------------------

2022-01-06 23:14:13,117 - mmgen - INFO - Distributed training: True
2022-01-06 23:14:13,247 - mmgen - INFO - Config:
dataset_type = 'UnconditionalImageDataset'
train_pipeline = [
    dict(type='LoadImageFromFile', key='real_img', io_backend='disk'),
    dict(type='Flip', keys=['real_img'], direction='horizontal'),
    dict(
        type='Normalize',
        keys=['real_img'],
        mean=[127.5, 127.5, 127.5],
        std=[127.5, 127.5, 127.5],
        to_rgb=False),
    dict(type='ImageToTensor', keys=['real_img']),
    dict(type='Collect', keys=['real_img'], meta_keys=['real_img_path'])
]
val_pipeline = [
    dict(type='LoadImageFromFile', key='real_img', io_backend='disk'),
    dict(
        type='Normalize',
        keys=['real_img'],
        mean=[127.5, 127.5, 127.5],
        std=[127.5, 127.5, 127.5],
        to_rgb=True),
    dict(type='ImageToTensor', keys=['real_img']),
    dict(type='Collect', keys=['real_img'], meta_keys=['real_img_path'])
]
data = dict(
    samples_per_gpu=4,
    workers_per_gpu=4,
    train=dict(
        type='RepeatDataset',
        times=100,
        dataset=dict(
            type='UnconditionalImageDataset',
            imgs_root='../../../data/raw/sample',
            pipeline=[
                dict(
                    type='LoadImageFromFile',
                    key='real_img',
                    io_backend='disk'),
                dict(type='Flip', keys=['real_img'], direction='horizontal'),
                dict(
                    type='Normalize',
                    keys=['real_img'],
                    mean=[127.5, 127.5, 127.5],
                    std=[127.5, 127.5, 127.5],
                    to_rgb=False),
                dict(type='ImageToTensor', keys=['real_img']),
                dict(
                    type='Collect',
                    keys=['real_img'],
                    meta_keys=['real_img_path'])
            ])),
    val=dict(
        type='UnconditionalImageDataset',
        imgs_root='../../../data/raw/sample',
        pipeline=[
            dict(type='LoadImageFromFile', key='real_img', io_backend='disk'),
            dict(
                type='Normalize',
                keys=['real_img'],
                mean=[127.5, 127.5, 127.5],
                std=[127.5, 127.5, 127.5],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['real_img']),
            dict(
                type='Collect', keys=['real_img'], meta_keys=['real_img_path'])
        ]))
d_reg_interval = 16
g_reg_interval = 4
g_reg_ratio = 0.8
d_reg_ratio = 0.9411764705882353
model = dict(
    type='StaticUnconditionalGAN',
    generator=dict(
        type='StyleGANv2Generator', out_size=256, style_channels=512),
    discriminator=dict(type='StyleGAN2Discriminator', in_size=256),
    gan_loss=dict(type='GANLoss', gan_type='wgan-logistic-ns'),
    disc_auxiliary_loss=dict(
        type='R1GradientPenalty',
        loss_weight=80.0,
        interval=16,
        norm_mode='HWC',
        data_info=dict(real_data='real_imgs', discriminator='disc')),
    gen_auxiliary_loss=dict(
        type='GeneratorPathRegularizer',
        loss_weight=8.0,
        pl_batch_shrink=2,
        interval=4,
        data_info=dict(generator='gen', num_batches='batch_size')))
train_cfg = dict(use_ema=True)
test_cfg = None
optimizer = dict(
    generator=dict(type='Adam', lr=0.0016, betas=(0, 0.9919919678228657)),
    discriminator=dict(
        type='Adam', lr=0.0018823529411764706, betas=(0, 0.9905854573074332)))
checkpoint_config = dict(interval=10000, by_epoch=False, max_keep_ckpts=30)
log_config = dict(interval=100, hooks=[dict(type='TextLoggerHook')])
custom_hooks = [
    dict(
        type='VisualizeUnconditionalSamples',
        output_dir='training_samples',
        interval=5000),
    dict(
        type='ExponentialMovingAverageHook',
        module_keys=('generator_ema', ),
        interval=1,
        interp_cfg=dict(momentum=0.9977843871238888),
        priority='VERY_HIGH')
]
runner = dict(
    type='DynamicIterBasedRunner',
    is_dynamic_ddp=True,
    pass_training_status=True)
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = '../../../model_zoo/mmgeneration/0.4.0/styleganv2/stylegan2_c2_ffhq_256_b4x8_20210407_160709-7890ae1f.pth'
resume_from = None
workflow = [('train', 10000)]
find_unused_parameters = True
cudnn_benchmark = True
ema_half_life = 10.0
lr_config = None
total_iters = 5000
metrics = dict(
    fid50k=dict(
        type='FID',
        num_images=40000,
        inception_pkl='../../../output/inception_pkl/caleba.pkl',
        bgr2rgb=True),
    pr50k3=dict(type='PR', num_images=40000, k=3),
    ppl_wend=dict(type='PPL', space='W', sampling='end', num_images=40000))
evaluation = dict(
    type='GenerativeEvalHook',
    interval=10000,
    metrics=dict(
        type='FID',
        num_images=40000,
        inception_pkl='../../../output/inception_pkl/caleba.pkl',
        bgr2rgb=True),
    sample_kwargs=dict(sample_model='ema'))
work_dir = './work_dirs/stylegan2_c2_ffhq_256_b4x8_800k'
gpu_ids = range(0, 2)

2022-01-06 23:14:13,247 - mmgen - INFO - Set random seed to 2021, deterministic: False
2022-01-06 23:14:15,078 - mmgen - INFO - dataset_name: <class 'mmgen.datasets.unconditional_image_dataset.UnconditionalImageDataset'>, total 40000 images in imgs_root: ../../../data/raw/sample
fatal: not a git repository (or any parent up to mount point /home/ma-user)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /home/ma-user)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2022-01-06 23:14:18,943 - mmgen - INFO - dataset_name: <class 'mmgen.datasets.unconditional_image_dataset.UnconditionalImageDataset'>, total 40000 images in imgs_root: ../../../data/raw/sample
/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/torchvision/models/inception.py:82: FutureWarning: The default weight initialization of inception_v3 will be changed in future releases of torchvision. If you wish to keep the old behavior (which leads to long initialization times due to scipy/scipy#11299), please set init_weights=True.
  ' due to scipy/scipy#11299), please set init_weights=True.', FutureWarning)
/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/torchvision/models/inception.py:82: FutureWarning: The default weight initialization of inception_v3 will be changed in future releases of torchvision. If you wish to keep the old behavior (which leads to long initialization times due to scipy/scipy#11299), please set init_weights=True.
  ' due to scipy/scipy#11299), please set init_weights=True.', FutureWarning)
2022-01-06 23:17:24,405 - mmgen - INFO - FID: Adopt Inception in pytorch style
2022-01-06 23:17:24,451 - mmgen - INFO - Load reference inception pkl from ../../../output/inception_pkl/caleba.pkl
2022-01-06 23:17:24,451 - mmgen - INFO - load checkpoint from local path: ../../../model_zoo/mmgeneration/0.4.0/styleganv2/stylegan2_c2_ffhq_256_b4x8_20210407_160709-7890ae1f.pth
2022-01-06 23:17:24,765 - mmgen - INFO - Start running, host: ma-user@notebook-8057cc96-2d5a-4a22-9d1f-754b14633e6b, work_dir: /home/ma-user/work/mmgen/algorithms/mmgeneration/algorithm/work_dirs/stylegan2_c2_ffhq_256_b4x8_800k
2022-01-06 23:17:24,765 - mmgen - INFO - workflow: [('train', 10000)], max: 5000 iters
2022-01-06 23:17:24,766 - mmgen - INFO - Checkpoints will be saved to ./work_dirs/stylegan2_c2_ffhq_256_b4x8_800k/ckpt/stylegan2_c2_ffhq_256_b4x8_800k by HardDiskBackend.
/home/ma-user/work/mmgen/algorithms/mmgeneration/algorithm/mmgen/ops/conv2d_gradfix.py:190: UserWarning: conv2d_gradfix not supported on PyTorch 1.9.0+cu102. Falling back to torch.nn.functional.conv2d().
  f'conv2d_gradfix not supported on PyTorch {torch.__version__}. '
/home/ma-user/work/mmgen/algorithms/mmgeneration/algorithm/mmgen/ops/conv2d_gradfix.py:190: UserWarning: conv2d_gradfix not supported on PyTorch 1.9.0+cu102. Falling back to torch.nn.functional.conv2d().
  f'conv2d_gradfix not supported on PyTorch {torch.__version__}. '
2022-01-06 23:19:30,464 - mmgen - INFO - Iter [100/5000]        lr_generator: 1.600e-03 lr_discriminator: 1.882e-03, eta: 1:22:01, time: 1.004, data_time: 0.003, memory: 12927, loss_disc_fake_g: 1.2576, loss_path_regular: 0.0464, loss: 1.1665, loss_disc_fake: 0.5016, loss_disc_real: 0.4978, loss_r1_gp: 2.3874
2022-01-06 23:21:01,678 - mmgen - INFO - Iter [200/5000]        lr_generator: 1.600e-03 lr_discriminator: 1.882e-03, eta: 1:16:39, time: 0.912, data_time: 0.003, memory: 12927, loss_disc_fake_g: 1.0306, loss_path_regular: 0.0424, loss: 1.2528, loss_disc_fake: 0.5724, loss_disc_real: 0.5765, loss_r1_gp: 2.0846
2022-01-06 23:22:32,770 - mmgen - INFO - Iter [300/5000]        lr_generator: 1.600e-03 lr_discriminator: 1.882e-03, eta: 1:13:49, time: 0.911, data_time: 0.003, memory: 12927, loss_disc_fake_g: 0.9520, loss_path_regular: 0.0407, loss: 1.2777, loss_disc_fake: 0.5932, loss_disc_real: 0.5889, loss_r1_gp: 1.9291
2022-01-06 23:24:03,901 - mmgen - INFO - Iter [400/5000]        lr_generator: 1.600e-03 lr_discriminator: 1.882e-03, eta: 1:11:39, time: 0.911, data_time: 0.003, memory: 12927, loss_disc_fake_g: 0.9833, loss_path_regular: 0.0393, loss: 1.2634, loss_disc_fake: 0.5889, loss_disc_real: 0.5915, loss_r1_gp: 1.7984
2022-01-06 23:25:35,512 - mmgen - INFO - Iter [500/5000]        lr_generator: 1.600e-03 lr_discriminator: 1.882e-03, eta: 1:09:49, time: 0.916, data_time: 0.003, memory: 12927, loss_disc_fake_g: 0.9344, loss_path_regular: 0.0372, loss: 1.2855, loss_disc_fake: 0.5944, loss_disc_real: 0.5857, loss_r1_gp: 1.7347

**Comment by LeoXing1996** [comment]
Hey, @ShoupingShan thanks for your interest in our project.
For GAN models, the training process is measured by how many images the model has seen. In an entire training process, the model is trained by `samples_per_gpu * N_GPUS * total_iteration` images.
Therefore, using more GPUs means you can reduce the `samples_per_gpu` and this can reduce the time cost for each iteration.

And to be noted that, in this setting, we use 8 GPUs and set batch size as 4 for each GPU (as `b4x8` in config name).

**Comment by ShoupingShan** [comment]
Thank you for your reply and your comments help me a lot.
