### ISSUE TITLE
CycleGAN inference

### ISSUE THREAD

**Issue by alessandro-ferreira** [open-mmlab/mmgeneration#210]
I'm using this code to performance an inference with the CycleGAN trained model available [here](https://github.com/open-mmlab/mmgeneration/tree/master/configs/cyclegan) for `horse2zebras`, but the resulting image I'm getting is not even close to the images shown on this page.

```python
import matplotlib.pyplot as plt
import numpy as np

import mmcv
from mmgen.apis import init_model, sample_img2img_model

# Specify the path to model config and checkpoint file
config_file = 'configs/cyclegan/cyclegan_lsgan_id0_resnet_in_horse2zebra_b1x1_270k.py'
checkpoint_file = 'https://download.openmmlab.com/mmgen/cyclegan/refactor/cyclegan_lsgan_id0_resnet_in_1x1_266800_horse2zebra_convert-bgr_20210902_165724-77c9c806.pth'

# Specify the path to image you want to translate'
image_path = 'tests/data/unpaired/testA/5.jpg'

device = 'cuda:0'
# init a generative
model = init_model(config_file, checkpoint_file, device=device)

# translate a single image
translated_image = sample_img2img_model(model, image_path, target_domain='zebra')

new_image = (translated_image[0] * 255).byte()
plt.imshow(new_image.permute(1, 2, 0).flip(-1))

plt.show()
```
![zebra](https://user-images.githubusercontent.com/29716229/148664724-3e125c51-d9b9-4e32-b5fe-dfcb529632bd.png)

Am I doing something wrong?
With `pip2pix` example worked fine.

**Comment by LeoXing1996** [comment]
Hi @alessandro-ferreira. thanks to interest in our project.

 In MMGeneration, the color channel order is 'BGR' and the model's output range is `[-1, 1]`.
Therefore, you should use the following code to visualize `translated_image`:
```python
new_image = (translated_image[0, [2, 1, 0]].permute(1, 2, 0) + 1) / 2 * 255.
```
You can also directly use `demo/translation_demo.py` to sample translation models.

**Comment by alessandro-ferreira** [comment]
Hi @LeoXing1996. Thanks a lot for the fast reply.

I didn't pay attention to the model's output range.
Your solution worked fine
```python
new_image = (translated_image[0, [2, 1, 0]].permute(1, 2, 0) + 1) / 2 * 255
plt.imshow(new_image.byte())
```
I also fixed my approach adjusting the output range
```python
new_image = ((translated_image[0] + 1.) / 2 * 255).byte()
plt.imshow(new_image.permute(1, 2, 0).flip(-1))
```

![zebra_fixed](https://user-images.githubusercontent.com/29716229/148672931-fb379ecb-605d-4c82-bb85-6a94e7f4944e.png)
