### ISSUE TITLE
Missing readme link in Installation Section

### ISSUE THREAD

**Issue by nikky4D** [open-mmlab/mmgeneration#225]
Minor issue

The link under "Installation" is broken. The link points to a md but there is nothing there. The md links is: https://github.com/open-mmlab/mmgeneration/blob/master/docs/get_started.md

**Comment by plyfager** [comment]
Hey @nikky4D , thanks for your interest in our project.
Check out this link: https://github.com/open-mmlab/mmgeneration/blob/master/docs/en/get_started.md 
I found a mistake [here](https://github.com/open-mmlab/mmgeneration#installation). Where else did you find this issue?

**Comment by zengyh1900** [comment]
Closing this issue since it has been fixed in https://github.com/open-mmlab/mmgeneration/pull/226
