### ISSUE TITLE
Error occurs at optimizer['generators'].step()

### ISSUE THREAD

**Issue by EdyQiu** [open-mmlab/mmgeneration#240]
Hello, I modified cyclegan model and set the generator's input channel from 3 to 4.
![image](https://user-images.githubusercontent.com/23387293/151704823-a2e82422-7d08-46ef-9ecb-4ce16f6e0a6d.png)
However, at optimizer['generators'].step(), the following error occurs:
RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1

I found the problem is due to this line: exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
exp_avg has dimension ([64, 3, 7, 7])  and grad has dimension  ([64, 4, 7, 7])
![image](https://user-images.githubusercontent.com/23387293/151704689-283cc406-c161-4271-9fa2-dfe83d3d9ce0.png)

Do you have any idea about why exp_avg 's second dimension is not 4?
Thanks for you help !

**Comment by LeoXing1996** [comment]
Hey @EdyQiu, `exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)` not appearance in our code. Can you provide more information about the code raise error and your Pytorch version?

**Comment by EdyQiu** [comment]
> Hey @EdyQiu, `exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)` not appear in our code. Can you provide more information about the code raise error and your Pytorch version?

**Thanks for your quick reply! 
The following is about my environment.** 
sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
CUDA_HOME: :/home/qiuxinkuan/cuda-10.1/:/home/qiuxinkuan/cuda-10.1/
GPU 0: TITAN Xp
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.7.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.0a0
OpenCV: 4.5.4
MMCV: 1.4.1
MMGen: 0.5.0+
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1

---------------------------------------------------------------------------------------------------------
**The following is the code got error reported. And the line is highlighted** 

r"""Functional interface"""
import math
import torch
from torch import Tensor
from typing import List

# TODO: use foreach API in optim.functional to do all the computation

def _make_sparse(grad, grad_indices, values):
    size = grad.size()
    if grad_indices.numel() == 0 or values.numel() == 0:
        return torch.empty_like(grad)
    return torch.sparse_coo_tensor(grad_indices, values, size)


def adagrad(params: List[Tensor],
            grads: List[Tensor],
            state_sums: List[Tensor],
            state_steps: List[int],
            lr: float,
            weight_decay: float,
            lr_decay: float,
            eps: float):
    r"""Functional API that performs Adagrad algorithm computation.

    See :class:`~torch.optim.Adagrad` for details.
    """

    for (param, grad, state_sum, step) in zip(params, grads, state_sums, state_steps):
        if weight_decay != 0:
            if grad.is_sparse:
                raise RuntimeError("weight_decay option is not compatible with sparse gradients")
            grad = grad.add(param, alpha=weight_decay)

        clr = lr / (1 + (step - 1) * lr_decay)

        if grad.is_sparse:
            grad = grad.coalesce()  # the update is non-linear so indices must be unique
            grad_indices = grad._indices()
            grad_values = grad._values()
            size = grad.size()

            state_sum.add_(_make_sparse(grad, grad_indices, grad_values.pow(2)))
            std = state_sum.sparse_mask(grad)
            std_values = std._values().sqrt_().add_(eps)
            param.add_(_make_sparse(grad, grad_indices, grad_values / std_values), alpha=-clr)
        else:
            state_sum.addcmul_(grad, grad, value=1)
            std = state_sum.sqrt().add_(eps)
            param.addcdiv_(grad, std, value=-clr)


def adam(params: List[Tensor],
         grads: List[Tensor],
         exp_avgs: List[Tensor],
         exp_avg_sqs: List[Tensor],
         max_exp_avg_sqs: List[Tensor],
         state_steps: List[int],
         amsgrad: bool,
         beta1: float,
         beta2: float,
         lr: float,
         weight_decay: float,
         eps: float):
    r"""Functional API that performs Adam algorithm computation.

    See :class:`~torch.optim.Adam` for details.
    """

    for i, param in enumerate(params):

        grad = grads[i]
        exp_avg = exp_avgs[i]
        exp_avg_sq = exp_avg_sqs[i]
        step = state_steps[i]
        if amsgrad:
            max_exp_avg_sq = max_exp_avg_sqs[i]

        bias_correction1 = 1 - beta1 ** step
        bias_correction2 = 1 - beta2 ** step

        if weight_decay != 0:
            grad = grad.add(param, alpha=weight_decay)

        # Decay the first and second moment running average coefficient
        **exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)**
        exp_avg_sq.mul_(beta2).addcmul_(grad, grad, value=1 - beta2)
        if amsgrad:
            # Maintains the maximum of all 2nd moment running avg. till now
            torch.maximum(max_exp_avg_sq, exp_avg_sq, out=max_exp_avg_sq)
            # Use the max. for normalizing running avg. of gradient
            denom = (max_exp_avg_sq.sqrt() / math.sqrt(bias_correction2)).add_(eps)
        else:
            denom = (exp_avg_sq.sqrt() / math.sqrt(bias_correction2)).add_(eps)

        step_size = lr / bias_correction1

        param.addcdiv_(exp_avg, denom, value=-step_size)

**Comment by EdyQiu** [comment]
![image](https://user-images.githubusercontent.com/23387293/151709422-b6e0351d-dbd3-47f0-b084-079e94b6e30b.png)
![image](https://user-images.githubusercontent.com/23387293/151709432-413fb6e8-de60-4ccf-8fae-6abb51eaae0d.png)
![image](https://user-images.githubusercontent.com/23387293/151709451-29a36e16-6c78-413b-9a30-ea41527abe36.png)

**Comment by EdyQiu** [comment]
> Hey @EdyQiu, `exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)` not appear in our code. Can you provide more information about the code raise error and your Pytorch version?

By the way, I noticed the input images have 3 channels only, and the additional channel is added at the "train forward" stage. Not really sure  whether this cause the problem mentioned or not.

**Comment by EdyQiu** [comment]
Sorry, I get to work today and find out I used a checkpoint file rather than training from scratch.
