### ISSUE TITLE
If can install it with docker, it will be easy

### ISSUE THREAD

**Issue by Kayce001** [open-mmlab/mmgeneration#243]
**Describe the feature**

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when [....].
Ex2. There is a recent paper [....], which is very helpful for [....].

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.
提供docker安装
**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmgeneration/blob/master/docker/Dockerfile

**Comment by Kayce001** [comment]
> https://github.com/open-mmlab/mmgeneration/blob/master/docker/Dockerfile

**when i try 'docker build -t gan .  ',facing below issue(i tried change sources.list):**

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libx/libxrender/libxrender-dev_0.9.10-1_amd64.deb  Connection failed [IP: 91.189.88.142 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/m/mesa/mesa-va-drivers_20.0.8-0ubuntu1~18.04.1_amd64.deb  Connection failed [IP: 91.189.88.142 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/m/mesa/mesa-vdpau-drivers_20.0.8-0ubuntu1~18.04.1_amd64.deb  Connection failed [IP: 91.189.88.152 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/n/ninja-build/ninja-build_1.8.2-1_amd64.deb  Connection failed [IP: 91.189.88.152 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/i/intel-vaapi-driver/i965-va-driver_2.1.0-0ubuntu1_amd64.deb  Connection failed [IP: 91.189.88.142 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/libv/libva/va-driver-all_2.1.0-3_amd64.deb  Connection failed [IP: 91.189.88.142 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libv/libvdpau/vdpau-driver-all_1.1.1-3ubuntu1_amd64.deb  Connection failed [IP: 91.189.88.142 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get update && apt-get install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6     && apt-get clean     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by LeoXing1996** [comment]
If your internet environment can not access to the original APT source, you can manually add mirror to your Dockerfile.
