### ISSUE TITLE
MMCV==1.5.1 is used but incompatible.

### ISSUE THREAD

**Issue by huangjiyi** [open-mmlab/mmgeneration#299]
Hi，I got an error after installing mmgen following the [introduction](https://github.com/open-mmlab/mmgeneration#installation). 
`AssertionError: MMCV==1.5.1 is used but incompatible. Please install mmcv>=1.3.0, <=1.5.0.`
Finally I reinstalled mmgen with `mmcv==1.5.0` and it works.

**Comment by LeoXing1996** [comment]
Hey @huangjiyi, thanks for your interest.
This will be fixed in https://github.com/open-mmlab/mmgeneration/pull/298.
