### ISSUE TITLE
what's the difference among GAN Interpolation, Projection and Manipulation?

### ISSUE THREAD

**Issue by ronghui19** [open-mmlab/mmgeneration#3]
I do not understand the difference when i looked at the GIFs above highlight section. Can anyone explain a little bit?

**Comment by plyfager** [comment]
Briefly speaking, suppose you have a GAN and denote its generator by `g`.
1. You have latent **a** and **b**. `Interpolation` refers to get  the generated image g(**a**+t(**b**-**a**)), 0<t<1.
2. You have an image `x`. `Projection` refers to find a latent `z` such that `g(z)` is similar to `x`.
3. You want to edit an image `g(z)`. `Manipulation` refers to find certain `d` such that `g(z+d)` only changes a certain attribute.
