### ISSUE TITLE
How to specify the gpu id?

### ISSUE THREAD

**Issue by huangjiyi** [open-mmlab/mmgeneration#303]
Hi, I want specify the gpu id when training StyleGAN2, But it never works. 
For example, I want to use gpu-1 with command `bash mmgeneration/tools/dist_train.sh config.py 1 --work-dir work_dir --gpu-id 1`, But it still use gpu-0. What should I do?
Thanks!

**Comment by LeoXing1996** [comment]
Please refers to https://github.com/open-mmlab/mmgeneration/issues/302#issuecomment-1134549787.
