### ISSUE TITLE
Resize format

### ISSUE THREAD

**Issue by chandlerbing65nm** [open-mmlab/mmgeneration#307]
https://github.com/open-mmlab/mmgeneration/blob/6bce6ed0315438b3f7955019a2c6a64078cfd0e8/configs/cyclegan/cyclegan_lsgan_resnet_in_summer2winter_b1x1_250k.py#L60

```python
    dict(
        type='Resize',
        keys=[f'img_{domain_a}', f'img_{domain_b}'],
        scale=(286, 286),
        interpolation='bicubic'),
```

I want to ask the format of Resize, is it ```scale=(height, width)``` ?

Also this:

```python
metrics = dict(
    FID=dict(type='FID', num_images=num_images, image_shape=(3, 256, 256)),
    IS=dict(
        type='IS',
        num_images=num_images,
        image_shape=(3, 256, 256),
        inception_args=dict(type='pytorch')))
```

`image_shape=(channels, height, width)` ?

**Comment by LeoXing1996** [comment]
For `Resize`:
* `scale=(width, height)` if `keep_ratio=False`
* `scale=resize_scale` if `keep_ratio=True`

For `Metric.IS`:
* `image_shape=(channels, height, width)`

**Comment by chandlerbing65nm** [comment]
> 

@LeoXing1996 how about for the `crop` ?

**Comment by LeoXing1996** [comment]
Size format for `crop` is `[height, weight]`, which is Inconsistency with `Resize`. 
We will refactor all pipelines in the next version (maybe in late june).
