### ISSUE TITLE
Error occurs when training pix2pix after 10000 iter

### ISSUE THREAD

**Issue by xiaojifu** [open-mmlab/mmgeneration#309]
**Describe the bug**
When i training a pix2pix model ,the error occurs after 10000 iter 

**Reproduction**

What command or script did you run?
        bash tools/dist_train.sh configs/pix2pix/pix2pix_vanilla_unet_bn_facades_b1x1_80k.py 1

Did you make any modifications on the code or config? Did you understand what you have modified?
        I haven't made any modifications on the config 

What dataset did you use?
        I use facades dataset download in http://efrosgans.eecs.berkeley.edu/pix2pix/datasets/facades.tar.gz

**Environment**
sys.platform: linux
Python: 3.7.13 (default, Mar 29 2022, 02:18:16) [GCC 7.5.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.4.r11.4/compiler.30300941_0
GPU 0: NVIDIA GeForce RTX 3090
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.11.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.12.0
OpenCV: 4.1.2
MMCV: 1.5.0
MMGen: 0.7.1+6bce6ed
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.3

The config information is as follows :
2022-05-26 19:10:18,105 - mmgen - INFO - Distributed training: True
2022-05-26 19:10:18,273 - mmgen - INFO - Config:
source_domain = 'mask'
target_domain = 'photo'
model = dict(
    type='Pix2Pix',
    generator=dict(
        type='UnetGenerator',
        in_channels=3,
        out_channels=3,
        num_down=8,
        base_channels=64,
        norm_cfg=dict(type='BN'),
        use_dropout=True,
        init_cfg=dict(type='normal', gain=0.02)),
    discriminator=dict(
        type='PatchDiscriminator',
        in_channels=6,
        base_channels=64,
        num_conv=3,
        norm_cfg=dict(type='BN'),
        init_cfg=dict(type='normal', gain=0.02)),
    gan_loss=dict(
        type='GANLoss',
        gan_type='vanilla',
        real_label_val=1.0,
        fake_label_val=0.0,
        loss_weight=1.0),
    default_domain='photo',
    reachable_domains=['photo'],
    related_domains=['photo', 'mask'],
    gen_auxiliary_loss=dict(
        type='L1Loss',
        loss_weight=100.0,
        loss_name='pixel_loss',
        data_info=dict(pred='fake_photo', target='real_photo'),
        reduction='mean'))
train_cfg = None
test_cfg = None
train_dataset_type = 'PairedImageDataset'
val_dataset_type = 'PairedImageDataset'
img_norm_cfg = dict(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
domain_a = 'photo'
domain_b = 'mask'
train_pipeline = [
    dict(
        type='LoadPairedImageFromFile',
        io_backend='disk',
        key='pair',
        domain_a='photo',
        domain_b='mask',
        flag='color'),
    dict(
        type='Resize',
        keys=['img_photo', 'img_mask'],
        scale=(286, 286),
        interpolation='bicubic'),
    dict(
        type='FixedCrop', keys=['img_photo', 'img_mask'],
        crop_size=(256, 256)),
    dict(type='Flip', keys=['img_photo', 'img_mask'], direction='horizontal'),
    dict(type='RescaleToZeroOne', keys=['img_photo', 'img_mask']),
    dict(
        type='Normalize',
        keys=['img_photo', 'img_mask'],
        to_rgb=False,
        mean=[0.5, 0.5, 0.5],
        std=[0.5, 0.5, 0.5]),
    dict(type='ImageToTensor', keys=['img_photo', 'img_mask']),
    dict(
        type='Collect',
        keys=['img_photo', 'img_mask'],
        meta_keys=['img_photo_path', 'img_mask_path'])
]
test_pipeline = [
    dict(
        type='LoadPairedImageFromFile',
        io_backend='disk',
        key='pair',
        domain_a='photo',
        domain_b='mask',
        flag='color'),
    dict(
        type='Resize',
        keys=['img_photo', 'img_mask'],
        scale=(256, 256),
        interpolation='bicubic'),
    dict(type='RescaleToZeroOne', keys=['img_photo', 'img_mask']),
    dict(
        type='Normalize',
        keys=['img_photo', 'img_mask'],
        to_rgb=False,
        mean=[0.5, 0.5, 0.5],
        std=[0.5, 0.5, 0.5]),
    dict(type='ImageToTensor', keys=['img_photo', 'img_mask']),
    dict(
        type='Collect',
        keys=['img_photo', 'img_mask'],
        meta_keys=['img_photo_path', 'img_mask_path'])
]
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=4,
    drop_last=True,
    train=dict(
        type='PairedImageDataset',
        dataroot='data/facades',
        pipeline=[
            dict(
                type='LoadPairedImageFromFile',
                io_backend='disk',
                key='pair',
                domain_a='photo',
                domain_b='mask',
                flag='color'),
            dict(
                type='Resize',
                keys=['img_photo', 'img_mask'],
                scale=(286, 286),
                interpolation='bicubic'),
            dict(
                type='FixedCrop',
                keys=['img_photo', 'img_mask'],
                crop_size=(256, 256)),
            dict(
                type='Flip',
                keys=['img_photo', 'img_mask'],
                direction='horizontal'),
            dict(type='RescaleToZeroOne', keys=['img_photo', 'img_mask']),
            dict(
                type='Normalize',
                keys=['img_photo', 'img_mask'],
                to_rgb=False,
                mean=[0.5, 0.5, 0.5],
                std=[0.5, 0.5, 0.5]),
            dict(type='ImageToTensor', keys=['img_photo', 'img_mask']),
            dict(
                type='Collect',
                keys=['img_photo', 'img_mask'],
                meta_keys=['img_photo_path', 'img_mask_path'])
        ],
        test_mode=False),
    val=dict(
        type='PairedImageDataset',
        dataroot='data/facades',
        pipeline=[
            dict(
                type='LoadPairedImageFromFile',
                io_backend='disk',
                key='pair',
                domain_a='photo',
                domain_b='mask',
                flag='color'),
            dict(
                type='Resize',
                keys=['img_photo', 'img_mask'],
                scale=(256, 256),
                interpolation='bicubic'),
            dict(type='RescaleToZeroOne', keys=['img_photo', 'img_mask']),
            dict(
                type='Normalize',
                keys=['img_photo', 'img_mask'],
                to_rgb=False,
                mean=[0.5, 0.5, 0.5],
                std=[0.5, 0.5, 0.5]),
            dict(type='ImageToTensor', keys=['img_photo', 'img_mask']),
            dict(
                type='Collect',
                keys=['img_photo', 'img_mask'],
                meta_keys=['img_photo_path', 'img_mask_path'])
        ],
        test_mode=True),
    test=dict(
        type='PairedImageDataset',
        dataroot='data/facades',
        pipeline=[
            dict(
                type='LoadPairedImageFromFile',
                io_backend='disk',
                key='pair',
                domain_a='photo',
                domain_b='mask',
                flag='color'),
            dict(
                type='Resize',
                keys=['img_photo', 'img_mask'],
                scale=(256, 256),
                interpolation='bicubic'),
            dict(type='RescaleToZeroOne', keys=['img_photo', 'img_mask']),
            dict(
                type='Normalize',
                keys=['img_photo', 'img_mask'],
                to_rgb=False,
                mean=[0.5, 0.5, 0.5],
                std=[0.5, 0.5, 0.5]),
            dict(type='ImageToTensor', keys=['img_photo', 'img_mask']),
            dict(
                type='Collect',
                keys=['img_photo', 'img_mask'],
                meta_keys=['img_photo_path', 'img_mask_path'])
        ],
        test_mode=True))
checkpoint_config = dict(interval=10000, by_epoch=False, save_optimizer=True)
log_config = dict(interval=100, hooks=[dict(type='TextLoggerHook')])
custom_hooks = [
    dict(
        type='MMGenVisualizationHook',
        output_dir='training_samples',
        res_name_list=['fake_photo'],
        interval=5000)
]
runner = None
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
find_unused_parameters = True
cudnn_benchmark = True
opencv_num_threads = 0
mp_start_method = 'fork'
dataroot = 'data/facades'
optimizer = dict(
    generators=dict(type='Adam', lr=0.0002, betas=(0.5, 0.999)),
    discriminators=dict(type='Adam', lr=0.0002, betas=(0.5, 0.999)))
lr_config = None
use_ddp_wrapper = True
total_iters = 80000
exp_name = 'pix2pix_facades'
work_dir = './work_dirs/experiments/pix2pix_facades'
num_images = 106
metrics = dict(
    FID=dict(type='FID', num_images=106, image_shape=(3, 256, 256)),
    IS=dict(
        type='IS',
        num_images=106,
        image_shape=(3, 256, 256),
        inception_args=dict(type='pytorch')))
evaluation = dict(
    type='TranslationEvalHook',
    target_domain='mask',
    interval=10000,
    metrics=[
        dict(type='FID', num_images=106, bgr2rgb=True),
        dict(type='IS', num_images=106, inception_args=dict(type='pytorch'))
    ],
    best_metric=['fid', 'is'])
gpu_ids = range(0, 1)
**Error traceback**

If applicable, paste the error trackback here.

2022-05-26 19:20:24,642 - mmgen - INFO - Sample 106 fake images for evaluation
[                                                  ] 0/106, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/train.py", line 228, in <module>
    main()
  File "tools/train.py", line 224, in main
    meta=meta)
  File "/home/hnu/Jinhu/Project/mmgeneration/mmgen/apis/train.py", line 207, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/hnu/anaconda3/envs/mmgeneration/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/hnu/anaconda3/envs/mmgeneration/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 67, in train
    self.call_hook('after_train_iter')
  File "/home/hnu/anaconda3/envs/mmgeneration/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/hnu/Jinhu/Project/mmgeneration/mmgen/core/evaluation/eval_hooks.py", line 485, in after_train_iter
    **self.sample_kwargs)
  File "/home/hnu/anaconda3/envs/mmgeneration/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hnu/Jinhu/Project/mmgeneration/mmgen/core/ddp_wrapper.py", line 111, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/hnu/anaconda3/envs/mmgeneration/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hnu/Jinhu/Project/mmgeneration/mmgen/models/translation_models/base_translation_model.py", line 80, in forward
    return self.forward_test(img, **kwargs)
  File "/home/hnu/Jinhu/Project/mmgeneration/mmgen/models/translation_models/pix2pix.py", line 36, in forward_test
    target = self.translation(img, target_domain=target_domain, **kwargs)
  File "/home/hnu/Jinhu/Project/mmgeneration/mmgen/models/translation_models/base_translation_model.py", line 137, in translation
    _model = self._get_target_generator(target_domain)
  File "/home/hnu/Jinhu/Project/mmgeneration/mmgen/models/translation_models/static_translation_gan.py", line 132, in _get_target_generator
    {self._reachable_domains}'
AssertionError: mask domain is not reachable, available domain list is            ['photo']
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 15289) of binary: /home/hnu/anaconda3/envs/mmgeneration/bin/python
Traceback (most recent call last):
  File "/home/hnu/anaconda3/envs/mmgeneration/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hnu/anaconda3/envs/mmgeneration/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hnu/anaconda3/envs/mmgeneration/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/hnu/anaconda3/envs/mmgeneration/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/hnu/anaconda3/envs/mmgeneration/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/hnu/anaconda3/envs/mmgeneration/lib/python3.7/site-packages/torch/distributed/run.py", line 718, in run
    )(*cmd_args)
  File "/home/hnu/anaconda3/envs/mmgeneration/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/hnu/anaconda3/envs/mmgeneration/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-05-26_19:20:27
  host      : hnu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 15289)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by plyfager** [comment]
Hi @xiaojifu, since the reachable_domain is `photo` in the model field, you should set `target_domain` to photo in the evaluation field.

**Comment by xiaojifu** [comment]
> Hi @xiaojifu, thx for your feedback. There is a bug in https://github.com/open-mmlab/mmgeneration/blob/master/configs/pix2pix/pix2pix_vanilla_unet_bn_facades_b1x1_80k.py#L121. Here `target_domain=target_domain` should replace `target_domain=domain_b`.

Thanks for your reply @ @plyfager
