### ISSUE TITLE
Improve DDPM的训练问题

### ISSUE THREAD

**Issue by Xwmiss** [open-mmlab/mmgeneration#314]
请问我在使用FFHQ数据来训练DDPM的时候，我的FFHQ数据只包含图片，没有其他的任何标注，我使用了'../_base_/datasets/unconditional_imgs_64x64.py'的数据读取设置，但是始终出现了以下错误，好像是没有读取到图片，请问这是为什么？
<img width="657" alt="image" src="https://user-images.githubusercontent.com/59326436/173372173-40e3545d-30aa-4849-a2e5-ed879955a010.png">

**Comment by Xwmiss** [comment]
> 请问我在使用FFHQ数据来训练DDPM的时候，我的FFHQ数据只包含图片，没有其他的任何标注，我使用了'../_base_/datasets/unconditional_imgs_64x64.py'的数据读取设置，但是始终出现了以下错误，好像是没有读取到图片，请问这是为什么？

Excuse me, when I use FFHQ data to train DDPM, my FFHQ data only contains images and not any other annotations, I use '... /base/datasets/unconditional_imgs_64x64.py' data read settings, but I always get the following error, it seems that the images are not read, why is this?

**Comment by LeoXing1996** [comment]
Can you provide your training config?

**Comment by Xwmiss** [comment]
> Can you provide your training config?

I have fix the previous problem, because the config has different setup.
