### ISSUE TITLE
Training stop in improved DDPM 

### ISSUE THREAD

**Issue by Xwmiss** [open-mmlab/mmgeneration#315]
I begin to train improved DDPM with my own dataset, while today i find the training stop with the problem blow. It seems like some problem with NCCL but I am not sure. Can you explicit it?
![image](https://user-images.githubusercontent.com/59326436/173481472-f1e0042d-c952-42a3-a51d-68ae4cf1c633.png)

**Comment by LeoXing1996** [comment]
This is a little weird. What kind of GPU device do you use? Can you successfully train other distributed tasks on this machine?

**Comment by Xwmiss** [comment]
> This is a little weird. What kind of GPU device do you use? Can you successfully train other distributed tasks on this machine?

I ues 8* 2080Ti with batch 18(18*8=144), I have trained on the code by OpenAI with 3 days last week. So I don't know what make this problem.

**Comment by Xwmiss** [comment]
> > This is a little weird. What kind of GPU device do you use? Can you successfully train other distributed tasks on this machine?
> 
> I ues 8* 2080Ti with batch 18(18*8=144), I have trained on the code by OpenAI with 3 days last week. So I don't know what make this problem.

Maybe is the batch is too big to make GPU make error?

**Comment by Xwmiss** [comment]
Today it occur again！

Traceback (most recent call last):
  File "tools/train.py", line 228, in <module>
    main()
  File "tools/train.py", line 224, in main
    meta=meta)
  File "/home/chenwen08/mmgeneration/mmgen/apis/train.py", line 207, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 285, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 215, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/chenwen08/mmgeneration/mmgen/core/ddp_wrapper.py", line 123, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 235, in train_step
    loss, log_vars = self._get_loss(denoising_dict_)
  File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 145, in _get_loss
    loss, log_vars = self._parse_losses(losses_dict)
  File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 182, in _parse_losses
    dist.all_reduce(loss_value.div_(dist.get_world_size()))
  File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1314, in all_reduce
    work = default_pg.allreduce([tensor], opts)
RuntimeError: NCCL communicator was aborted on rank 7.  Original reason for failure was: [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1565462, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1801302 milliseconds before timing out.
Traceback (most recent call last):
  File "tools/train.py", line 228, in <module>
Traceback (most recent call last):
  File "tools/train.py", line 228, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "tools/train.py", line 228, in <module>
  File "tools/train.py", line 228, in <module>
Traceback (most recent call last):
  File "tools/train.py", line 228, in <module>
    main()
  File "tools/train.py", line 224, in main
    meta=meta)
  File "/home/chenwen08/mmgeneration/mmgen/apis/train.py", line 207, in train_model
    main()
  File "tools/train.py", line 224, in main
Traceback (most recent call last):
        main()    main()runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "tools/train.py", line 228, in <module>


  File "tools/train.py", line 224, in main
  File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 285, in run
    meta=meta)
  File "/home/chenwen08/mmgeneration/mmgen/apis/train.py", line 207, in train_model
  File "tools/train.py", line 224, in main
        iter_runner(iter_loaders[i], **kwargs)
  File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 215, in train
    meta=meta)
  File "/home/chenwen08/mmgeneration/mmgen/apis/train.py", line 207, in train_model
    main()runner.run(data_loaders, cfg.workflow, cfg.total_iters)

  File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 285, in run
      File "tools/train.py", line 224, in main
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 285, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 215, in train
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 215, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)    
main()meta=meta)  File "/home/chenwen08/mmgeneration/mmgen/core/ddp_wrapper.py", line 123, in train_step

  File "tools/train.py", line 224, in main
        outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)  File "/home/chenwen08/mmgeneration/mmgen/core/ddp_wrapper.py", line 123, in train_step


  File "/home/chenwen08/mmgeneration/mmgen/apis/train.py", line 207, in train_model
      File "/home/chenwen08/mmgeneration/mmgen/core/ddp_wrapper.py", line 123, in train_step
        meta=meta)output = self.module.train_step(*inputs[0], **kwargs[0])meta=meta)

  File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 235, in train_step
    
output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 235, in train_step
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 285, in run
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 235, in train_step
    loss, log_vars = self._get_loss(denoising_dict_)
      File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 145, in _get_loss
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 215, in train
    loss, log_vars = self._get_loss(denoising_dict_)
  File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 145, in _get_loss
    loss, log_vars = self._parse_losses(losses_dict)
  File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 182, in _parse_losses
loss, log_vars = self._get_loss(denoising_dict_)
  File "/home/chenwen08/mmgeneration/mmgen/apis/train.py", line 207, in train_model
  File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 145, in _get_loss
  File "/home/chenwen08/mmgeneration/mmgen/apis/train.py", line 207, in train_model
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
      File "/home/chenwen08/mmgeneration/mmgen/core/ddp_wrapper.py", line 123, in train_step
dist.all_reduce(loss_value.div_(dist.get_world_size()))
      File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1314, in all_reduce
loss, log_vars = self._parse_losses(losses_dict)    
loss, log_vars = self._parse_losses(losses_dict)  File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 182, in _parse_losses

  File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 182, in _parse_losses
            runner.run(data_loaders, cfg.workflow, cfg.total_iters)output = self.module.train_step(*inputs[0], **kwargs[0])runner.run(data_loaders, cfg.workflow, cfg.total_iters)

  File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 235, in train_step

      File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 285, in run
dist.all_reduce(loss_value.div_(dist.get_world_size()))    loss, log_vars = self._get_loss(denoising_dict_)    
  File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 145, in _get_loss
iter_runner(iter_loaders[i], **kwargs)

  File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1314, in all_reduce
  File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 215, in train
    work = default_pg.allreduce([tensor], opts)
RuntimeError: NCCL communicator was aborted on rank 1.  Original reason for failure was: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1565462, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1800947 milliseconds before timing out.
  File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 285, in run
        dist.all_reduce(loss_value.div_(dist.get_world_size()))
loss, log_vars = self._parse_losses(losses_dict)
  File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1314, in all_reduce
  File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 182, in _parse_losses
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/chenwen08/mmgeneration/mmgen/core/ddp_wrapper.py", line 123, in train_step
    dist.all_reduce(loss_value.div_(dist.get_world_size()))
  File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1314, in all_reduce
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 215, in train
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 235, in train_step
    work = default_pg.allreduce([tensor], opts)    
outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/chenwen08/mmgeneration/mmgen/core/ddp_wrapper.py", line 123, in train_step
RuntimeError    loss, log_vars = self._get_loss(denoising_dict_)
  File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 145, in _get_loss
: NCCL communicator was aborted on rank 2.  Original reason for failure was: [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1565462, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1801051 milliseconds before timing out.
            work = default_pg.allreduce([tensor], opts)output = self.module.train_step(*inputs[0], **kwargs[0])loss, log_vars = self._parse_losses(losses_dict)


  File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 182, in _parse_losses
RuntimeError  File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 235, in train_step
    dist.all_reduce(loss_value.div_(dist.get_world_size()))
  File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1314, in all_reduce
:     NCCL communicator was aborted on rank 3.  Original reason for failure was: [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1565462, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1801065 milliseconds before timing out.work = default_pg.allreduce([tensor], opts)

RuntimeError: NCCL communicator was aborted on rank 6.  Original reason for failure was: [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1565462, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1800715 milliseconds before timing out.
    loss, log_vars = self._get_loss(denoising_dict_)
  File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 145, in _get_loss
    loss, log_vars = self._parse_losses(losses_dict)
  File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 182, in _parse_losses
    dist.all_reduce(loss_value.div_(dist.get_world_size()))
  File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1314, in all_reduce
    work = default_pg.allreduce([tensor], opts)
RuntimeError: NCCL communicator was aborted on rank 4.  Original reason for failure was: [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1565462, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1800759 milliseconds before timing out.
    work = default_pg.allreduce([tensor], opts)
RuntimeError: NCCL communicator was aborted on rank 5.  Original reason for failure was: [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1565462, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1800856 mi(mmlab) root@kml-dtmachine-8940-prod:/home/chenwen08/mmgeneration# WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 119556 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 119557) of binary: /opt/conda/envs/mmlab/bin/python
Traceback (most recent call last):
  File "/opt/conda/envs/mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 718, in run
    )(*cmd_args)
  File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-06-15_10:00:15
  host      : kml-dtmachine-8940-prod
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 119558)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2022-06-15_10:00:15
  host      : kml-dtmachine-8940-prod
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 119559)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2022-06-15_10:00:15
  host      : kml-dtmachine-8940-prod
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 119560)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2022-06-15_10:00:15
  host      : kml-dtmachine-8940-prod
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 119561)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2022-06-15_10:00:15
  host      : kml-dtmachine-8940-prod
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 119562)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2022-06-15_10:00:15
  host      : kml-dtmachine-8940-prod
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 119563)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-06-15_10:00:15
  host      : kml-dtmachine-8940-prod
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 119557)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================       ^C
[1]+  Exit 1                  bash tools/dist_train.sh /home/chenwen08/mmgeneration/configs/improved_ddpm/ddpm_cosine_hybird_timestep-4k_drop0.3_ffhq_64x64.py 8

**Comment by Xwmiss** [comment]
> Today it occur again！
> 
> Traceback (most recent call last): File "tools/train.py", line 228, in main() File "tools/train.py", line 224, in main meta=meta) File "/home/chenwen08/mmgeneration/mmgen/apis/train.py", line 207, in train_model runner.run(data_loaders, cfg.workflow, cfg.total_iters) File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 285, in run iter_runner(iter_loaders[i], **kwargs) File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 215, in train outputs = self.model.train_step(data_batch, self.optimizer, **kwargs) File "/home/chenwen08/mmgeneration/mmgen/core/ddp_wrapper.py", line 123, in train_step output = self.module.train_step(*inputs[0], **kwargs[0]) File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 235, in train_step loss, log_vars = self._get_loss(denoising_dict_) File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 145, in _get_loss loss, log_vars = self._parse_losses(losses_dict) File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 182, in _parse_losses dist.all_reduce(loss_value.div_(dist.get_world_size())) File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1314, in all_reduce work = default_pg.allreduce([tensor], opts) RuntimeError: NCCL communicator was aborted on rank 7. Original reason for failure was: [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1565462, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1801302 milliseconds before timing out. Traceback (most recent call last): File "tools/train.py", line 228, in Traceback (most recent call last): File "tools/train.py", line 228, in Traceback (most recent call last): Traceback (most recent call last): File "tools/train.py", line 228, in File "tools/train.py", line 228, in Traceback (most recent call last): File "tools/train.py", line 228, in main() File "tools/train.py", line 224, in main meta=meta) File "/home/chenwen08/mmgeneration/mmgen/apis/train.py", line 207, in train_model main() File "tools/train.py", line 224, in main Traceback (most recent call last): main() main()runner.run(data_loaders, cfg.workflow, cfg.total_iters) File "tools/train.py", line 228, in
> 
> File "tools/train.py", line 224, in main File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 285, in run meta=meta) File "/home/chenwen08/mmgeneration/mmgen/apis/train.py", line 207, in train_model File "tools/train.py", line 224, in main iter_runner(iter_loaders[i], **kwargs) File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 215, in train meta=meta) File "/home/chenwen08/mmgeneration/mmgen/apis/train.py", line 207, in train_model main()runner.run(data_loaders, cfg.workflow, cfg.total_iters)
> 
> File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 285, in run File "tools/train.py", line 224, in main runner.run(data_loaders, cfg.workflow, cfg.total_iters) File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 285, in run iter_runner(iter_loaders[i], **kwargs) File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 215, in train iter_runner(iter_loaders[i], **kwargs) File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 215, in train outputs = self.model.train_step(data_batch, self.optimizer, **kwargs) main()meta=meta) File "/home/chenwen08/mmgeneration/mmgen/core/ddp_wrapper.py", line 123, in train_step
> 
> File "tools/train.py", line 224, in main outputs = self.model.train_step(data_batch, self.optimizer, **kwargs) outputs = self.model.train_step(data_batch, self.optimizer, **kwargs) File "/home/chenwen08/mmgeneration/mmgen/core/ddp_wrapper.py", line 123, in train_step
> 
> File "/home/chenwen08/mmgeneration/mmgen/apis/train.py", line 207, in train_model File "/home/chenwen08/mmgeneration/mmgen/core/ddp_wrapper.py", line 123, in train_step meta=meta)output = self.module.train_step(*inputs[0], **kwargs[0])meta=meta)
> 
> File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 235, in train_step
> 
> output = self.module.train_step(*inputs[0], **kwargs[0]) File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 235, in train_step runner.run(data_loaders, cfg.workflow, cfg.total_iters) File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 285, in run output = self.module.train_step(*inputs[0], **kwargs[0]) File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 235, in train_step loss, log_vars = self._get_loss(denoising_dict_) File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 145, in _get_loss iter_runner(iter_loaders[i], **kwargs) File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 215, in train loss, log_vars = self._get_loss(denoising_dict_) File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 145, in _get_loss loss, log_vars = self._parse_losses(losses_dict) File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 182, in _parse_losses loss, log_vars = self._get_loss(denoising_dict_) File "/home/chenwen08/mmgeneration/mmgen/apis/train.py", line 207, in train_model File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 145, in _get_loss File "/home/chenwen08/mmgeneration/mmgen/apis/train.py", line 207, in train_model outputs = self.model.train_step(data_batch, self.optimizer, **kwargs) File "/home/chenwen08/mmgeneration/mmgen/core/ddp_wrapper.py", line 123, in train_step dist.all_reduce(loss_value.div_(dist.get_world_size())) File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1314, in all_reduce loss, log_vars = self._parse_losses(losses_dict) loss, log_vars = self._parse_losses(losses_dict) File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 182, in _parse_losses
> 
> File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 182, in _parse_losses runner.run(data_loaders, cfg.workflow, cfg.total_iters)output = self.module.train_step(*inputs[0], **kwargs[0])runner.run(data_loaders, cfg.workflow, cfg.total_iters)
> 
> File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 235, in train_step
> 
> ```
>   File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 285, in run
> ```
> 
> dist.all_reduce(loss_value.div_(dist.get_world_size())) loss, log_vars = self._get_loss(denoising_dict_) File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 145, in _get_loss iter_runner(iter_loaders[i], **kwargs)
> 
> File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1314, in all_reduce File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 215, in train work = default_pg.allreduce([tensor], opts) RuntimeError: NCCL communicator was aborted on rank 1. Original reason for failure was: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1565462, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1800947 milliseconds before timing out. File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 285, in run dist.all_reduce(loss_value.div_(dist.get_world_size())) loss, log_vars = self._parse_losses(losses_dict) File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1314, in all_reduce File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 182, in _parse_losses outputs = self.model.train_step(data_batch, self.optimizer, **kwargs) File "/home/chenwen08/mmgeneration/mmgen/core/ddp_wrapper.py", line 123, in train_step dist.all_reduce(loss_value.div_(dist.get_world_size())) File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1314, in all_reduce iter_runner(iter_loaders[i], **kwargs) File "/home/chenwen08/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 215, in train output = self.module.train_step(*inputs[0], **kwargs[0]) File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 235, in train_step work = default_pg.allreduce([tensor], opts) outputs = self.model.train_step(data_batch, self.optimizer, **kwargs) File "/home/chenwen08/mmgeneration/mmgen/core/ddp_wrapper.py", line 123, in train_step RuntimeError loss, log_vars = self._get_loss(denoising_dict_) File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 145, in _get_loss : NCCL communicator was aborted on rank 2. Original reason for failure was: [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1565462, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1801051 milliseconds before timing out. work = default_pg.allreduce([tensor], opts)output = self.module.train_step(*inputs[0], **kwargs[0])loss, log_vars = self._parse_losses(losses_dict)
> 
> File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 182, in _parse_losses RuntimeError File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 235, in train_step dist.all_reduce(loss_value.div_(dist.get_world_size())) File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1314, in all_reduce : NCCL communicator was aborted on rank 3. Original reason for failure was: [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1565462, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1801065 milliseconds before timing out.work = default_pg.allreduce([tensor], opts)
> 
> RuntimeError: NCCL communicator was aborted on rank 6. Original reason for failure was: [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1565462, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1800715 milliseconds before timing out. loss, log_vars = self._get_loss(denoising_dict_) File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 145, in _get_loss loss, log_vars = self._parse_losses(losses_dict) File "/home/chenwen08/mmgeneration/mmgen/models/diffusions/base_diffusion.py", line 182, in _parse_losses dist.all_reduce(loss_value.div_(dist.get_world_size())) File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1314, in all_reduce work = default_pg.allreduce([tensor], opts) RuntimeError: NCCL communicator was aborted on rank 4. Original reason for failure was: [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1565462, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1800759 milliseconds before timing out. work = default_pg.allreduce([tensor], opts) RuntimeError: NCCL communicator was aborted on rank 5. Original reason for failure was: [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1565462, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1800856 mi(mmlab) root@kml-dtmachine-8940-prod:/home/chenwen08/mmgeneration# WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 119556 closing signal SIGTERM ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 119557) of binary: /opt/conda/envs/mmlab/bin/python Traceback (most recent call last): File "/opt/conda/envs/mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "/opt/conda/envs/mmlab/lib/python3.7/runpy.py", line 85, in _run_code exec(code, run_globals) File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in main() File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main launch(args) File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch run(args) File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 718, in run )(*cmd_args) File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in **call** return launch_agent(self._config, self._entrypoint, list(args)) File "/opt/conda/envs/mmlab/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent failures=result.failures, torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

I don't konw what happen in training。。。。
