### ISSUE TITLE
[Feature Request] Add namespace when registering VisualizationHook and DistributedDataParallelWrapper

### ISSUE THREAD

**Issue by RangiLyu** [open-mmlab/mmgeneration#32]
mmedit and mmgen both have VisualizationHook, mmpose and mmgen both haveDistributedDataParallelWrapper. It would be better to register these hooks in a namespace to avoid key-value conflict.

**Comment by nbei** [comment]
Thanks @RangiLyu . We will consider fixing it in the next week.
