### ISSUE TITLE
怎样将CycleGAN中的L1损失替换成PerceptualLoss？

### ISSUE THREAD

**Issue by lurchycc** [open-mmlab/mmgeneration#328]

**Comment by plyfager** [comment]
Hi @lurchycc, you can define an `PerceptualLoss` class under `mmgen/models/losses/gen_auxiliary_loss.py` and register it into `MODULES`. Then just change `gen_auxiliary_loss` of your config like below:
```
model=dict(
xxx,
gen_auxiliary_loss=dict(
        type='PerceptualLoss',
        loss_weight=1.0,
        loss_name='per_loss',
        data_info=dict(
            pred=f'fake_{target_domain}', target=f'real_{target_domain}'),
        reduction='mean'))
```

**Comment by lurchycc** [comment]
> Hi @lurchycc, you can define an `PerceptualLoss` class under `mmgen/models/losses/gen_auxiliary_loss.py` and register it into `MODULES`. Then just change `gen_auxiliary_loss` of your config like below:
> 
> ```
> model=dict(
> xxx,
> gen_auxiliary_loss=dict(
>         type='PerceptualLoss',
>
