### ISSUE TITLE
Pretrained discriminator for BigGAN of 256 and 512?

### ISSUE THREAD

**Issue by IceClear** [open-mmlab/mmgeneration#403]
Hi. I just wonder if there are pretrained discriminators for BigGAN under 256 and 512 size? Currently, only the corresponding pretrained  generators are avaliable. Thanks.

**Comment by plyfager** [comment]
Hi @IceClear , we do not have pretrained discriminators for biggan 256 or 512, maybe you can just refer to https://github.com/huggingface/pytorch-pretrained-BigGAN. We would appreciate it a lot if you'd like offer converted weights.
