### ISSUE TITLE
How to do transfer learning on mmgeneration framework?

### ISSUE THREAD

**Issue by ronghui19** [open-mmlab/mmgeneration#41]
I already pepared my own dataset and downloaded ffhq_256 checkpoint. what should i modify to get started transfer learning?

**Comment by nbei** [comment]
Hi @ronghui19 , I think you may want to tune the model in your own dataset. Is it right?

### Prepare dataset
As claimed in your comments, you should modify or directly use the dataset config. I recommend that you can take [this config](https://github.com/open-mmlab/mmgeneration/blob/master/configs/_base_/datasets/unconditional_imgs_flip_256x256.py) as a reference.

### Modify training config
Next, we should prepare your own config based on the original [FFHQ-256 config](https://github.com/open-mmlab/mmgeneration/blob/master/configs/styleganv2/stylegan2_c2_ffhq_256_b4x8_800k.py). Suppose that your own data is saved in `data/custom_data` and the pre-trained ckpt is saved in `work_dirs/cache/stylegan_ffhq-256.pth`. You should modify the config file like this:

```python
"""Config for the `config-f` setting in StyleGAN2."""
_base_ = ['../_base_/datasets/your_own_dataset.py',
'../_base_/models/stylegan2_base.py',
'../_base_/default_runtime.py']

model = dict(generator=dict(out_size=256), discriminator=dict(in_size=256))

# modifiy the data source
data = dict(samples_per_gpu=4,
train=dict(dataset=dict(imgs_root='./data/custom_data')),
val=dict(imgs_root='./data/custom_data'))

# here, you may copy some part of the code from the original config file
# like: custom_hooks, evaluation, checkpoint_config, lr_config, and so on.

total_iters = xxx

load_from = 'work_dirs/cache/stylegan_ffhq-256.pth'

```
If other questions, welcome to leave a comment.

**Comment by ronghui19** [comment]
`"""Config for the `config-f` setting in StyleGAN2."""

_base_ = [
    '../_base_/datasets/ffhq_flip.py', '../_base_/models/stylegan2_base.py',
    '../_base_/default_runtime.py'
]

model = dict(generator=dict(out_size=256), discriminator=dict(in_size=256))

data = dict(
    samples_per_gpu=4,
    train=dict(dataset=dict(imgs_root='/home/roy/data/prepared_imgs2561/')),
    val=dict(imgs_root='/home/roy/data/prepared_imgs256/'))

ema_half_life = 10.  # G_smoothing_kimg

custom_hooks = [
    dict(
        type='VisualizeUnconditionalSamples',
        output_dir='training_samples',
        interval=1000),
    dict(
        type='ExponentialMovingAverageHook',
        module_keys=('generator_ema', ),
        interval=1,
        interp_cfg=dict(momentum=0.5**(32. / (ema_half_life * 1000.))),
        priority='VERY_HIGH')
]

checkpoint_config = dict(interval=2000, by_epoch=False, max_keep_ckpts=30)
lr_config = None

log_config = dict(
    interval=100,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook'),
    ])

total_iters = 25000

metrics = dict(
    fid50k=dict(
        type='FID',
        num_images=36058,
        inception_pkl='work_dirs/inception_pkl/stylegan2_c2_ffhq_256_b4x8_20210407_160709-7890ae1f.pth',
        bgr2rgb=True),
    pr50k3=dict(type='PR', num_images=36058, k=3),
    ppl_wend=dict(type='PPL', space='W', sampling='end', num_images=36058))

evaluation = dict(
    type='GenerativeEvalHook',
    interval=1000,
    metrics=dict(
        type='FID',
        num_images=36058,
        inception_pkl='work_dirs/inception_pkl/stylegan2_c2_ffhq_256_b4x8_20210407_160709-7890ae1f.pth',
        bgr2rgb=True),
    sample_kwargs=dict(sample_model='ema'))

load_from = '/home/roy/mmlab/mmgeneration/work_dirs/inception_pkl/\
    stylegan2_c2_ffhq_256_b4x8_20210407_160709-7890ae1f.pth'`

I followed your instruction.  Somehow i got following error. The command i used is _python tools/train.py configs/styleganv2/styleganv2_mycase.py --gpu-ids 1_

 _**__pickle.UnpicklingError: GenerativeEvalHook: A load persistent id instruction was encountered, but no persistent_load function was specified._**_

**Comment by nbei** [comment]
## Training command
In `MMGeneration`, we only support distributed training now. Thus, you would better follow the instructions in this [tutorial](https://mmgeneration.readthedocs.io/en/latest/quick_run.html#train-existing-models). In a word, you may train your model with `tools/dist_train.sh`:

```bash
bash tools/dist_train.sh ${GPU_NUM} ${CONFIG} --work-dir ${EXP_PATH}
```
## Errors in config file
This line in your configuration file is not right:

```python
inception_pkl='work_dirs/inception_pkl/stylegan2_c2_ffhq_256_b4x8_20210407_160709-7890ae1f.pth'
```
The checkpoint downloaded from our website is not `inception_pkl`. `inception_pkl` is used for quickly calculating `FID` metric. If you are not familiar with FID, you can first remove the `evaluation` part in your config file.
