### ISSUE TITLE
KeyError: 'SiLU is already registered in activation layer'

### ISSUE THREAD

**Issue by kakachake** [open-mmlab/mmgeneration#444]
当我将环境安装好后，使用示例代码出现如下错误：
KeyError: 'SiLU is already registered in activation layer'

**Comment by limlogin** [comment]
me too

**Comment by plyfager** [comment]
This is a bug due to `SiLU` is registered in `mmcv`. We will fix it soon.

**Comment by LeoXing1996** [comment]
This will be fixed in #447.

**Comment by LeoXing1996** [comment]
Close this issue since #447 has been merged to MASTER.
