### ISSUE TITLE
[Bug] Non-distributed Training Error

### ISSUE THREAD

**Issue by MrPeterJin** [open-mmlab/mmgeneration#493]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmgeneration/issues) and [Discussions](https://github.com/open-mmlab/mmgeneration/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmgeneration.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmgeneration).

### Task

I have modified the scripts/configs or I'm working on my own tasks/models/datasets.

### Environment

```
sys.platform: linux
Python: 3.9.13 (main, Aug 25 2022, 23:26:10) [GCC 11.2.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.6.r11.6/compiler.30794723_0
GPU 0,1,2,3,4,5,6,7: NVIDIA GeForce RTX 3090
GCC: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
PyTorch: 1.13.1+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.14.1+cu117
OpenCV: 4.7.0
MMCV: 1.7.0
MMGen: 0.7.2+f9f00fd
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.7
```

### Reproduces the problem - code sample

```python
python train.py $config --work-dir=$self-defined --gpu-id $gpu-id
```

### Reproduces the problem - command or script

```python
python train.py $config --work-dir=$self-defined --gpu-id $gpu-id
```

### Reproduces the problem - error message

```
work_dir = $work-dir
gpu_ids = $gpu-id

2023-01-31 16:12:05,441 - mmgen - INFO - Set random seed to 2021, deterministic: False, use_rank_shift: False
2023-01-31 16:12:06,494 - mmgen - INFO - dataset_name: <class 'mmgen.datasets.unconditional_image_dataset.UnconditionalImageDataset'>, total 12 images in imgs_root: $img_root
2023-01-31 16:12:09,320 - mmgen - INFO - Start running, host: $host, work_dir: $work-dir
2023-01-31 16:12:09,323 - mmgen - INFO - workflow: [('train', 10000)], max: 1500002 iters
2023-01-31 16:12:09,325 - mmgen - INFO - Checkpoints will be saved to $user/dcgan/ckpt/dcgan by HardDiskBackend.

Traceback (most recent call last):
  File "/mmgeneration/tools/train.py", line 228, in <module>
    main()
  File "/mmgeneration/tools/train.py", line 217, in main
    train_model(
  File "/mmgeneration/mmgen/apis/train.py", line 207, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 285, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 207, in train
    kwargs.update(dict(ddp_reducer=self.model.reducer))
  File "/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'MMDataParallel' object has no attribute 'reducer'
```

### Additional information

Since the dataset is small, it cannot run on distributed settings. However, when I tried non-distributed mode, it raise the error. Please help.

**Comment by MrPeterJin** [comment]
By the way, I have referred to https://github.com/open-mmlab/mmgeneration/issues/26#issuecomment-842832695 and it temporarily worked, Can you fix the DDP wrapper problem?

**Comment by LeoXing1996** [comment]
Hey @MrPeterJin. Sorry for the late response. MMGeneration has been merged into [MMEditing dev-1.x](https://github.com/open-mmlab/mmediting/tree/dev-1.x). We strongly encourage you to use MMEditing dev-1.x, since distributed training and AMP training are better supported.

**Comment by MrPeterJin** [comment]
Hi, actually I *have* refer to the MMEditing repo and found that Image Generation Methods (i.e., DCGAN, PGAN) from MMGeneration are not included. Therefore I turned to this repo. Maybe the team can handle this?

**Comment by MrPeterJin** [comment]
> Hey @MrPeterJin. Sorry for the late response. MMGeneration has been merged into [MMEditing dev-1.x](https://github.com/open-mmlab/mmediting/tree/dev-1.x). We strongly encourage you to use MMEditing dev-1.x, since distributed training and AMP training are better supported.

Hi, actually I have refer to the MMEditing repo and found that Image Generation Methods (i.e., DCGAN, PGAN) from MMGeneration are not included. Therefore I turned to this repo. Maybe the team can handle this?

**Comment by LeoXing1996** [comment]
Hey @MrPeterJin, please make sure that you are using **dev-1.x** branch of MMEditing, configs and models for DCGAN and PGGAN can be found in the following URL:
* DCGAN: [config](https://github.com/open-mmlab/mmediting/tree/dev-1.x/configs/dcgan), [model](https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/dcgan/dcgan.py)
* PGGAN: [config](https://github.com/open-mmlab/mmediting/tree/dev-1.x/configs/pggan), [model](https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/pggan/pggan.py)

**Comment by MrPeterJin** [comment]
> Hey @MrPeterJin, please make sure that you are using **dev-1.x** branch of MMEditing, configs and models for DCGAN and PGGAN can be found in the following URL:
> 
> * DCGAN: [config](https://github.com/open-mmlab/mmediting/tree/dev-1.x/configs/dcgan), [model](https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/dcgan/dcgan.py)
> * PGGAN: [config](https://github.com/open-mmlab/mmediting/tree/dev-1.x/configs/pggan), [model](https://github.com/open-mmlab/mmediting/blob/dev-1.x/mmedit/models/editors/pggan/pggan.py)

Thanks, I would look into that!
