### ISSUE TITLE
How to generate visualization results for `pix2pix` model

### ISSUE THREAD

**Issue by yinchimaoliang** [open-mmlab/mmgeneration#50]
Hello!

I used the `configs/pix2pix/pix2pix_vanilla_unet_bn_1x1_80k_facades.py` config to train and got the expected checkpoints. But when I tried to use the checkpoints to generate visualization results for valid datasets, all scripts under the `apps` folder and `tools/evaluation.py` didn't work, May I ask that how to generate visualization results for the `pix2pix` model？

Thanks in advance.

**Comment by plyfager** [comment]
Hi @yinchimaoliang , if you want to generate visualization results for translation models (now we only support `pix2pix` and `cyclegan` ), I may suggest two ways:
1. Using `demo/translation_demo.py` for inference, you can follow the instructions [here](https://mmgeneration.readthedocs.io/en/latest/quick_run.html?highlight=translation_eval#sample-images-with-image-translation-models).
2. Using `tools/utils/translation_eval.py` script. For example, you can run the following instruction.
```python
python tools/utils/translation_eval.py ./configs/pix2pix/pix2pix_vanilla_unet_bn_1x1_80k_facades.py https://download.openmmlab.com/mmgen/pix2pix/pix2pix_vanilla_unet_bn_1x1_80k_facades.py_20210410_174537-36d956f1.pth --samples-path ./work_dirs/path_to_samples/
```
Then you can see the generated samples in `./work_dirs/path_to_samples/`.
By the way, all scripts under `apps` folder do not support translation models. In detail, `interpolate_sample.py` supports all unconditional models. `modified_sefa.py` and `stylegan_projector.py` only support Style-Based models.
