### ISSUE TITLE
will data augmentation affect model performance?

### ISSUE THREAD

**Issue by ronghui19** [open-mmlab/mmgeneration#56]
Because of the need of more data, i want to use data augmentation. There is a question. If i rotate many images, will styleganv2 generate rotated images too? If that is a case, that is not what i want. So what is correct way to augment images?

**Comment by nbei** [comment]
[StyleGAN-ADA](https://arxiv.org/abs/2006.06676) has discussed this problem. Meanwhile, [Diffaug](https://arxiv.org/abs/2006.10738) is also a good solution to deal with this problem. We will support these two data augmentation in the future. In fact, it is easy for users to add these two data augmentations in our `MMGeneration`.
