### ISSUE TITLE
in the test file,(1,3,8,8)'s encoding is (1,8,8,8),so how to add the (1,3,8,8) and (1,8,8,8)?

### ISSUE THREAD

**Issue by hexinxin109** [open-mmlab/mmgeneration#77]

**Comment by nbei** [comment]
Could you provide more details about this issue?

**Comment by hexinxin109** [comment]
Dear Rui Xu:
&nbsp; &nbsp; &nbsp; &nbsp;I'm sorry to take you a few minutes.I'd like to ask some questions in the code.In the test_pe.py, I find that if the tensor is (1,3,8,8),the spe 2d will return a tensor(1,8,8,8). So how to combine (1,8,8,8) with (1,3,8,8), maybe the question is how to combine the input tensor with its positional encoding? In the test_singan_archs.py, it use"head_grid=self.head_position_encode; noise_ += head_grid",but the channel of (1,3,8,8)and (1,8,8,8) is 3 and 8,so "+" will report errors.
&nbsp; &nbsp; &nbsp; I am looking forword to your reply,thank you!



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmgeneration"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月27日(星期二) 中午1:56
***@***.***&gt;;
抄送:&nbsp;"@***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmgeneration] in the test file,(1,3,8,8)'s encoding is (1,8,8,8),so how to add the (1,3,8,8) and (1,8,8,8)? (#77)





 
Could you provide more details about this issue?

**Comment by nbei** [comment]
Thanks for your interest in our project. In the detailed implementation, we will change the input noise dimension according to the positional encodings. You may refer to this [config](https://github.com/open-mmlab/mmgeneration/blob/master/configs/positional_encoding_in_gans/singan_spe-dim4_bohemian.py#L12) for a better understanding.

**Comment by hexinxin109** [comment]
However，just for the SinGan, in the scale n , it will reconstruct an image,whose output channels are 3, and then when it is used in the next scale n+1 ,how to change the channel into 8 ?

**Comment by nbei** [comment]
We only adopt positional encodings at the start noise tensor. You can refer to this [part](https://github.com/open-mmlab/mmgeneration/blob/master/mmgen/models/architectures/singan/positional_encoding.py#L190) for the detailed implementation. In this version, we do not inject positional encoding in the intermediate noises, because there is a scaler in the intermediate noise tensors. It always contains a small value which prevents the positional encoding from making a difference.

**Comment by hexinxin109** [comment]
Thank you for your help, you have solved my question!
