### ISSUE TITLE
Generated images got oil painting style and is blurry

### ISSUE THREAD

**Issue by anheidelonghu** [open-mmlab/mmgeneration#79]
I trained the StyleGAN2 about 140k iterations(samples_per_gpu=3, px=1024), and visualized the **training result**. I found the generated images tend to be oil painting style and is a little blurry. What can I do to avoid these phenomenon?
Looking forward to your reply, thanks!
![5_cvt](https://user-images.githubusercontent.com/21210269/127252533-dfdc37c3-6ec0-4c4f-9fa4-cc19b4d4a86e.png)

**Comment by nbei** [comment]
Training such high-resolution stylegan2 needs much training cost. I may suggest that you can use `samples_per_gpu=4` and adopt 8 GPUs as the standard setting. Could you tell me more about the training details, e.g., the number of GPUs, current fid, and etc?

**Comment by anheidelonghu** [comment]
The number of GPUs is 8, samples_per_gpu=3, current FID50k is about 120, maybe there are some bugs in my implement...

**Comment by nbei** [comment]
Do you directly run our configs or use your own implementation?

**Comment by anheidelonghu** [comment]
I use my own implementation.

**Comment by nbei** [comment]
How many iterations have you trained your models for? Maybe I can share some results in our experiments to help you.

**Comment by anheidelonghu** [comment]
Thank you for your help! The current iteration is about 168k, loss_disc_fake_g is about 3.6(in the range of 1.8~2.4), loss_disc_real is 0.28(in the range of 0.1~0.7),  loss_disc_fake is about 0.4(in the range of 0.1~0.7), loss_path_regular is about 1.1(increasing while training), loss_r1_gp is about 2.4.

**Comment by anheidelonghu** [comment]
Thank you for your help! The current iteration is about 168k, loss_disc_fake_g is about 3.6(in the range of 1.8 to 2.4), loss_disc_real is 0.28(in the range of 0.1 to 0.7), loss_disc_fake is about 0.4(in the range of 0.1 to 0.7), loss_path_regular is about 1.1(increasing while training), loss_r1_gp is about 2.4.

**Comment by nbei** [comment]
I check out experiments and the fid in 16w iteration is 5.3657. 

loss_disc_fake_g: about 1.5
loss_disc_fake: about 0.385

**Comment by anheidelonghu** [comment]
Thank you for your reply, I'll check my implementation.
