### ISSUE TITLE
Default training config of CycleGAN summer2winter issuse.

### ISSUE THREAD

**Issue by zeyu-hello** [open-mmlab/mmgeneration#98]
Hi, I use default config: `configs/cyclegan/cyclegan_lsgan_resnet_in_1x1_250k_summer2winter.py`
but I got below training log, why generators' loss goes up?
![image](https://user-images.githubusercontent.com/29373801/130409194-3bc47d3f-07c3-42dc-93e9-45ef48e5ed92.png)

thx!

**Comment by plyfager** [comment]
Hi @[zeyu-hello](https://github.com/zeyu-hello), can you provide generated samples with iteration information?
